// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"postgresql-cluster-console/models"
)

// GetClustersIDQueryPerformanceOKCode is the HTTP code returned for type GetClustersIDQueryPerformanceOK
const GetClustersIDQueryPerformanceOKCode int = 200

// GetClustersIDQueryPerformanceOK OK
//
// swagger:response getClustersIdQueryPerformanceOK
type GetClustersIDQueryPerformanceOK struct {

	// In: Body
	Payload *models.ResponseQueryPerformance `json:"body,omitempty"`
}

// NewGetClustersIDQueryPerformanceOK creates GetClustersIDQueryPerformanceOK with default headers values
func NewGetClustersIDQueryPerformanceOK() *GetClustersIDQueryPerformanceOK {

	return &GetClustersIDQueryPerformanceOK{}
}

// WithPayload adds the payload to the get clusters Id query performance o k response
func (o *GetClustersIDQueryPerformanceOK) WithPayload(payload *models.ResponseQueryPerformance) *GetClustersIDQueryPerformanceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters Id query performance o k response
func (o *GetClustersIDQueryPerformanceOK) SetPayload(payload *models.ResponseQueryPerformance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersIDQueryPerformanceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClustersIDQueryPerformanceBadRequestCode is the HTTP code returned for type GetClustersIDQueryPerformanceBadRequest
const GetClustersIDQueryPerformanceBadRequestCode int = 400

// GetClustersIDQueryPerformanceBadRequest Error
//
// swagger:response getClustersIdQueryPerformanceBadRequest
type GetClustersIDQueryPerformanceBadRequest struct {

	// In: Body
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewGetClustersIDQueryPerformanceBadRequest creates GetClustersIDQueryPerformanceBadRequest with default headers values
func NewGetClustersIDQueryPerformanceBadRequest() *GetClustersIDQueryPerformanceBadRequest {

	return &GetClustersIDQueryPerformanceBadRequest{}
}

// WithPayload adds the payload to the get clusters Id query performance bad request response
func (o *GetClustersIDQueryPerformanceBadRequest) WithPayload(payload *models.ResponseError) *GetClustersIDQueryPerformanceBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters Id query performance bad request response
func (o *GetClustersIDQueryPerformanceBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersIDQueryPerformanceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
