// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetClustersIDQueryPerformanceHandlerFunc turns a function with the right signature into a get clusters ID query performance handler
type GetClustersIDQueryPerformanceHandlerFunc func(GetClustersIDQueryPerformanceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClustersIDQueryPerformanceHandlerFunc) Handle(params GetClustersIDQueryPerformanceParams) middleware.Responder {
	return fn(params)
}

// GetClustersIDQueryPerformanceHandler interface for that can handle valid get clusters ID query performance params
type GetClustersIDQueryPerformanceHandler interface {
	Handle(GetClustersIDQueryPerformanceParams) middleware.Responder
}

// NewGetClustersIDQueryPerformance creates a new http.Handler for the get clusters ID query performance operation
func NewGetClustersIDQueryPerformance(ctx *middleware.Context, handler GetClustersIDQueryPerformanceHandler) *GetClustersIDQueryPerformance {
	return &GetClustersIDQueryPerformance{Context: ctx, Handler: handler}
}

// GetClustersIDQueryPerformance swagger:route GET /clusters/{id}/query-performance cluster getClustersIdQueryPerformance
//
// Get cluster query performance overview
type GetClustersIDQueryPerformance struct {
	Context *middleware.Context
	Handler GetClustersIDQueryPerformanceHandler
}

func (o *GetClustersIDQueryPerformance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetClustersIDQueryPerformanceParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
