// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetClustersIDHealthHandlerFunc turns a function with the right signature into a get clusters ID health handler
type GetClustersIDHealthHandlerFunc func(GetClustersIDHealthParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClustersIDHealthHandlerFunc) Handle(params GetClustersIDHealthParams) middleware.Responder {
	return fn(params)
}

// GetClustersIDHealthHandler interface for that can handle valid get clusters ID health params
type GetClustersIDHealthHandler interface {
	Handle(GetClustersIDHealthParams) middleware.Responder
}

// NewGetClustersIDHealth creates a new http.Handler for the get clusters ID health operation
func NewGetClustersIDHealth(ctx *middleware.Context, handler GetClustersIDHealthHandler) *GetClustersIDHealth {
	return &GetClustersIDHealth{Context: ctx, Handler: handler}
}

// GetClustersIDHealth swagger:route GET /clusters/{id}/health cluster getClustersIdHealth
//
// Get cluster health snapshot
type GetClustersIDHealth struct {
	Context *middleware.Context
	Handler GetClustersIDHealthHandler
}

func (o *GetClustersIDHealth) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetClustersIDHealthParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
