// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag/conv"
)

// GetClustersIDHealthURL generates an URL for the get clusters ID health operation
type GetClustersIDHealthURL struct {
	ID int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetClustersIDHealthURL) WithBasePath(bp string) *GetClustersIDHealthURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetClustersIDHealthURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetClustersIDHealthURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/clusters/{id}/health"

	id := conv.FormatInteger(o.ID)
	if id != "" {
		_path = strings.ReplaceAll(_path, "{id}", id)
	} else {
		return nil, errors.New("id is required on GetClustersIDHealthURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetClustersIDHealthURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetClustersIDHealthURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetClustersIDHealthURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetClustersIDHealthURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetClustersIDHealthURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetClustersIDHealthURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
