// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetClustersIDQueryPerformanceFingerprintIDHandlerFunc turns a function with the right signature into a get clusters ID query performance fingerprint ID handler
type GetClustersIDQueryPerformanceFingerprintIDHandlerFunc func(GetClustersIDQueryPerformanceFingerprintIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClustersIDQueryPerformanceFingerprintIDHandlerFunc) Handle(params GetClustersIDQueryPerformanceFingerprintIDParams) middleware.Responder {
	return fn(params)
}

// GetClustersIDQueryPerformanceFingerprintIDHandler interface for that can handle valid get clusters ID query performance fingerprint ID params
type GetClustersIDQueryPerformanceFingerprintIDHandler interface {
	Handle(GetClustersIDQueryPerformanceFingerprintIDParams) middleware.Responder
}

// NewGetClustersIDQueryPerformanceFingerprintID creates a new http.Handler for the get clusters ID query performance fingerprint ID operation
func NewGetClustersIDQueryPerformanceFingerprintID(ctx *middleware.Context, handler GetClustersIDQueryPerformanceFingerprintIDHandler) *GetClustersIDQueryPerformanceFingerprintID {
	return &GetClustersIDQueryPerformanceFingerprintID{Context: ctx, Handler: handler}
}

// GetClustersIDQueryPerformanceFingerprintID swagger:route GET /clusters/{id}/query-performance/{fingerprint_id} cluster getClustersIdQueryPerformanceFingerprintId
//
// Get query performance detail
type GetClustersIDQueryPerformanceFingerprintID struct {
	Context *middleware.Context
	Handler GetClustersIDQueryPerformanceFingerprintIDHandler
}

func (o *GetClustersIDQueryPerformanceFingerprintID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetClustersIDQueryPerformanceFingerprintIDParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
