// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
	"github.com/go-openapi/validate"
)

// NewGetClustersIDQueryPerformanceParams creates a new GetClustersIDQueryPerformanceParams object
//
// There are no default values defined in the spec.
func NewGetClustersIDQueryPerformanceParams() GetClustersIDQueryPerformanceParams {

	return GetClustersIDQueryPerformanceParams{}
}

// GetClustersIDQueryPerformanceParams contains all the bound params for the get clusters ID query performance operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetClustersIDQueryPerformance
type GetClustersIDQueryPerformanceParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
	// In: query
	Application *string
	// In: query
	Database *string
	// In: query
	From *strfmt.DateTime
	// Required: true
	// In: path
	ID int64
	// In: query
	Role *string
	// In: query
	ServerID *int64
	// In: query
	To *strfmt.DateTime
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetClustersIDQueryPerformanceParams() beforehand.
func (o *GetClustersIDQueryPerformanceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r
	qs := runtime.Values(r.URL.Query())

	qApplication, qhkApplication, _ := qs.GetOK("application")
	if err := o.bindApplication(qApplication, qhkApplication, route.Formats); err != nil {
		res = append(res, err)
	}

	qDatabase, qhkDatabase, _ := qs.GetOK("database")
	if err := o.bindDatabase(qDatabase, qhkDatabase, route.Formats); err != nil {
		res = append(res, err)
	}

	qFrom, qhkFrom, _ := qs.GetOK("from")
	if err := o.bindFrom(qFrom, qhkFrom, route.Formats); err != nil {
		res = append(res, err)
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	qRole, qhkRole, _ := qs.GetOK("role")
	if err := o.bindRole(qRole, qhkRole, route.Formats); err != nil {
		res = append(res, err)
	}

	qServerID, qhkServerID, _ := qs.GetOK("server_id")
	if err := o.bindServerID(qServerID, qhkServerID, route.Formats); err != nil {
		res = append(res, err)
	}

	qTo, qhkTo, _ := qs.GetOK("to")
	if err := o.bindTo(qTo, qhkTo, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindApplication binds and validates parameter Application from query.
func (o *GetClustersIDQueryPerformanceParams) bindApplication(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Application = &raw

	return nil
}

// bindDatabase binds and validates parameter Database from query.
func (o *GetClustersIDQueryPerformanceParams) bindDatabase(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Database = &raw

	return nil
}

// bindFrom binds and validates parameter From from query.
func (o *GetClustersIDQueryPerformanceParams) bindFrom(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: date-time
	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("from", "query", "strfmt.DateTime", raw)
	}
	o.From = (value.(*strfmt.DateTime))

	if err := o.validateFrom(formats); err != nil {
		return err
	}

	return nil
}

// validateFrom carries out validations for parameter From
func (o *GetClustersIDQueryPerformanceParams) validateFrom(formats strfmt.Registry) error {

	if err := validate.FormatOf("from", "query", "date-time", o.From.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindID binds and validates parameter ID from path.
func (o *GetClustersIDQueryPerformanceParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := conv.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("id", "path", "int64", raw)
	}
	o.ID = value

	return nil
}

// bindRole binds and validates parameter Role from query.
func (o *GetClustersIDQueryPerformanceParams) bindRole(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Role = &raw

	return nil
}

// bindServerID binds and validates parameter ServerID from query.
func (o *GetClustersIDQueryPerformanceParams) bindServerID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := conv.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("server_id", "query", "int64", raw)
	}
	o.ServerID = &value

	return nil
}

// bindTo binds and validates parameter To from query.
func (o *GetClustersIDQueryPerformanceParams) bindTo(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: date-time
	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("to", "query", "strfmt.DateTime", raw)
	}
	o.To = (value.(*strfmt.DateTime))

	if err := o.validateTo(formats); err != nil {
		return err
	}

	return nil
}

// validateTo carries out validations for parameter To
func (o *GetClustersIDQueryPerformanceParams) validateTo(formats strfmt.Registry) error {

	if err := validate.FormatOf("to", "query", "date-time", o.To.String(), formats); err != nil {
		return err
	}
	return nil
}
