// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"postgresql-cluster-console/models"
)

// GetClustersIDQueryPerformanceFingerprintIDOKCode is the HTTP code returned for type GetClustersIDQueryPerformanceFingerprintIDOK
const GetClustersIDQueryPerformanceFingerprintIDOKCode int = 200

// GetClustersIDQueryPerformanceFingerprintIDOK OK
//
// swagger:response getClustersIdQueryPerformanceFingerprintIdOK
type GetClustersIDQueryPerformanceFingerprintIDOK struct {

	// In: Body
	Payload *models.ResponseQueryPerformanceDetail `json:"body,omitempty"`
}

// NewGetClustersIDQueryPerformanceFingerprintIDOK creates GetClustersIDQueryPerformanceFingerprintIDOK with default headers values
func NewGetClustersIDQueryPerformanceFingerprintIDOK() *GetClustersIDQueryPerformanceFingerprintIDOK {

	return &GetClustersIDQueryPerformanceFingerprintIDOK{}
}

// WithPayload adds the payload to the get clusters Id query performance fingerprint Id o k response
func (o *GetClustersIDQueryPerformanceFingerprintIDOK) WithPayload(payload *models.ResponseQueryPerformanceDetail) *GetClustersIDQueryPerformanceFingerprintIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters Id query performance fingerprint Id o k response
func (o *GetClustersIDQueryPerformanceFingerprintIDOK) SetPayload(payload *models.ResponseQueryPerformanceDetail) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersIDQueryPerformanceFingerprintIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClustersIDQueryPerformanceFingerprintIDBadRequestCode is the HTTP code returned for type GetClustersIDQueryPerformanceFingerprintIDBadRequest
const GetClustersIDQueryPerformanceFingerprintIDBadRequestCode int = 400

// GetClustersIDQueryPerformanceFingerprintIDBadRequest Error
//
// swagger:response getClustersIdQueryPerformanceFingerprintIdBadRequest
type GetClustersIDQueryPerformanceFingerprintIDBadRequest struct {

	// In: Body
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewGetClustersIDQueryPerformanceFingerprintIDBadRequest creates GetClustersIDQueryPerformanceFingerprintIDBadRequest with default headers values
func NewGetClustersIDQueryPerformanceFingerprintIDBadRequest() *GetClustersIDQueryPerformanceFingerprintIDBadRequest {

	return &GetClustersIDQueryPerformanceFingerprintIDBadRequest{}
}

// WithPayload adds the payload to the get clusters Id query performance fingerprint Id bad request response
func (o *GetClustersIDQueryPerformanceFingerprintIDBadRequest) WithPayload(payload *models.ResponseError) *GetClustersIDQueryPerformanceFingerprintIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters Id query performance fingerprint Id bad request response
func (o *GetClustersIDQueryPerformanceFingerprintIDBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersIDQueryPerformanceFingerprintIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
