// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"postgresql-cluster-console/models"
)

// GetClustersIDHealthOKCode is the HTTP code returned for type GetClustersIDHealthOK
const GetClustersIDHealthOKCode int = 200

// GetClustersIDHealthOK OK
//
// swagger:response getClustersIdHealthOK
type GetClustersIDHealthOK struct {

	// In: Body
	Payload *models.ResponseClusterHealth `json:"body,omitempty"`
}

// NewGetClustersIDHealthOK creates GetClustersIDHealthOK with default headers values
func NewGetClustersIDHealthOK() *GetClustersIDHealthOK {

	return &GetClustersIDHealthOK{}
}

// WithPayload adds the payload to the get clusters Id health o k response
func (o *GetClustersIDHealthOK) WithPayload(payload *models.ResponseClusterHealth) *GetClustersIDHealthOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters Id health o k response
func (o *GetClustersIDHealthOK) SetPayload(payload *models.ResponseClusterHealth) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersIDHealthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClustersIDHealthBadRequestCode is the HTTP code returned for type GetClustersIDHealthBadRequest
const GetClustersIDHealthBadRequestCode int = 400

// GetClustersIDHealthBadRequest Error
//
// swagger:response getClustersIdHealthBadRequest
type GetClustersIDHealthBadRequest struct {

	// In: Body
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewGetClustersIDHealthBadRequest creates GetClustersIDHealthBadRequest with default headers values
func NewGetClustersIDHealthBadRequest() *GetClustersIDHealthBadRequest {

	return &GetClustersIDHealthBadRequest{}
}

// WithPayload adds the payload to the get clusters Id health bad request response
func (o *GetClustersIDHealthBadRequest) WithPayload(payload *models.ResponseError) *GetClustersIDHealthBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters Id health bad request response
func (o *GetClustersIDHealthBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersIDHealthBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
