// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// GetClustersIDQueryPerformanceURL generates an URL for the get clusters ID query performance operation
type GetClustersIDQueryPerformanceURL struct {
	ID int64

	Application *string
	Database    *string
	From        *strfmt.DateTime
	Role        *string
	ServerID    *int64
	To          *strfmt.DateTime

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetClustersIDQueryPerformanceURL) WithBasePath(bp string) *GetClustersIDQueryPerformanceURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetClustersIDQueryPerformanceURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetClustersIDQueryPerformanceURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/clusters/{id}/query-performance"

	id := conv.FormatInteger(o.ID)
	if id != "" {
		_path = strings.ReplaceAll(_path, "{id}", id)
	} else {
		return nil, errors.New("id is required on GetClustersIDQueryPerformanceURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var applicationQ string
	if o.Application != nil {
		applicationQ = *o.Application
	}
	if applicationQ != "" {
		qs.Set("application", applicationQ)
	}

	var databaseQ string
	if o.Database != nil {
		databaseQ = *o.Database
	}
	if databaseQ != "" {
		qs.Set("database", databaseQ)
	}

	var fromQ string
	if o.From != nil {
		fromQ = o.From.String()
	}
	if fromQ != "" {
		qs.Set("from", fromQ)
	}

	var roleQ string
	if o.Role != nil {
		roleQ = *o.Role
	}
	if roleQ != "" {
		qs.Set("role", roleQ)
	}

	var serverIDQ string
	if o.ServerID != nil {
		serverIDQ = conv.FormatInteger(*o.ServerID)
	}
	if serverIDQ != "" {
		qs.Set("server_id", serverIDQ)
	}

	var toQ string
	if o.To != nil {
		toQ = o.To.String()
	}
	if toQ != "" {
		qs.Set("to", toQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetClustersIDQueryPerformanceURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetClustersIDQueryPerformanceURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetClustersIDQueryPerformanceURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetClustersIDQueryPerformanceURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetClustersIDQueryPerformanceURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetClustersIDQueryPerformanceURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
