// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	stderrors "errors"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
	"postgresql-cluster-console/models"
)

// NewPatchClustersIDRoutingParams creates a new PatchClustersIDRoutingParams object
//
// There are no default values defined in the spec.
func NewPatchClustersIDRoutingParams() PatchClustersIDRoutingParams {

	return PatchClustersIDRoutingParams{}
}

// PatchClustersIDRoutingParams contains all the bound params for the patch clusters ID routing operation
// typically these are obtained from a http.Request
//
// swagger:parameters PatchClustersIDRouting
type PatchClustersIDRoutingParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
	// Required: true
	// In: body
	Body models.RequestClusterRouting
	// Required: true
	// In: path
	ID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPatchClustersIDRoutingParams() beforehand.
func (o *PatchClustersIDRoutingParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer func() {
			_ = r.Body.Close()
		}()
		var body models.RequestClusterRouting
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if stderrors.Is(err, io.EOF) {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// no validation on generic interface
			o.Body = body
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindID binds and validates parameter ID from path.
func (o *PatchClustersIDRoutingParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := conv.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("id", "path", "int64", raw)
	}
	o.ID = value

	return nil
}
