// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"postgresql-cluster-console/models"
)

// PatchClustersIDRoutingOKCode is the HTTP code returned for type PatchClustersIDRoutingOK
const PatchClustersIDRoutingOKCode int = 200

// PatchClustersIDRoutingOK OK
//
// swagger:response patchClustersIdRoutingOK
type PatchClustersIDRoutingOK struct {

	// In: Body
	Payload *models.ClusterInfo `json:"body,omitempty"`
}

// NewPatchClustersIDRoutingOK creates PatchClustersIDRoutingOK with default headers values
func NewPatchClustersIDRoutingOK() *PatchClustersIDRoutingOK {

	return &PatchClustersIDRoutingOK{}
}

// WithPayload adds the payload to the patch clusters Id routing o k response
func (o *PatchClustersIDRoutingOK) WithPayload(payload *models.ClusterInfo) *PatchClustersIDRoutingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch clusters Id routing o k response
func (o *PatchClustersIDRoutingOK) SetPayload(payload *models.ClusterInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchClustersIDRoutingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchClustersIDRoutingBadRequestCode is the HTTP code returned for type PatchClustersIDRoutingBadRequest
const PatchClustersIDRoutingBadRequestCode int = 400

// PatchClustersIDRoutingBadRequest Error
//
// swagger:response patchClustersIdRoutingBadRequest
type PatchClustersIDRoutingBadRequest struct {

	// In: Body
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewPatchClustersIDRoutingBadRequest creates PatchClustersIDRoutingBadRequest with default headers values
func NewPatchClustersIDRoutingBadRequest() *PatchClustersIDRoutingBadRequest {

	return &PatchClustersIDRoutingBadRequest{}
}

// WithPayload adds the payload to the patch clusters Id routing bad request response
func (o *PatchClustersIDRoutingBadRequest) WithPayload(payload *models.ResponseError) *PatchClustersIDRoutingBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch clusters Id routing bad request response
func (o *PatchClustersIDRoutingBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchClustersIDRoutingBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
