// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchClustersIDRoutingHandlerFunc turns a function with the right signature into a patch clusters ID routing handler
type PatchClustersIDRoutingHandlerFunc func(PatchClustersIDRoutingParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchClustersIDRoutingHandlerFunc) Handle(params PatchClustersIDRoutingParams) middleware.Responder {
	return fn(params)
}

// PatchClustersIDRoutingHandler interface for that can handle valid patch clusters ID routing params
type PatchClustersIDRoutingHandler interface {
	Handle(PatchClustersIDRoutingParams) middleware.Responder
}

// NewPatchClustersIDRouting creates a new http.Handler for the patch clusters ID routing operation
func NewPatchClustersIDRouting(ctx *middleware.Context, handler PatchClustersIDRoutingHandler) *PatchClustersIDRouting {
	return &PatchClustersIDRouting{Context: ctx, Handler: handler}
}

// PatchClustersIDRouting swagger:route PATCH /clusters/{id}/routing cluster patchClustersIdRouting
//
// Update cluster routing metadata
type PatchClustersIDRouting struct {
	Context *middleware.Context
	Handler PatchClustersIDRoutingHandler
}

func (o *PatchClustersIDRouting) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewPatchClustersIDRoutingParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
