// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostClustersIDRestartHandlerFunc turns a function with the right signature into a post clusters ID restart handler
type PostClustersIDRestartHandlerFunc func(PostClustersIDRestartParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostClustersIDRestartHandlerFunc) Handle(params PostClustersIDRestartParams) middleware.Responder {
	return fn(params)
}

// PostClustersIDRestartHandler interface for that can handle valid post clusters ID restart params
type PostClustersIDRestartHandler interface {
	Handle(PostClustersIDRestartParams) middleware.Responder
}

// NewPostClustersIDRestart creates a new http.Handler for the post clusters ID restart operation
func NewPostClustersIDRestart(ctx *middleware.Context, handler PostClustersIDRestartHandler) *PostClustersIDRestart {
	return &PostClustersIDRestart{Context: ctx, Handler: handler}
}

// PostClustersIDRestart swagger:route POST /clusters/{id}/restart cluster postClustersIdRestart
//
// Restart cluster
type PostClustersIDRestart struct {
	Context *middleware.Context
	Handler PostClustersIDRestartHandler
}

func (o *PostClustersIDRestart) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewPostClustersIDRestartParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
