// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"postgresql-cluster-console/models"
)

// PostClustersIDPreflightsCreatedCode is the HTTP code returned for type PostClustersIDPreflightsCreated
const PostClustersIDPreflightsCreatedCode int = 201

// PostClustersIDPreflightsCreated Created
//
// swagger:response postClustersIdPreflightsCreated
type PostClustersIDPreflightsCreated struct {

	// In: Body
	Payload *models.ResponseOperationPreflight `json:"body,omitempty"`
}

// NewPostClustersIDPreflightsCreated creates PostClustersIDPreflightsCreated with default headers values
func NewPostClustersIDPreflightsCreated() *PostClustersIDPreflightsCreated {

	return &PostClustersIDPreflightsCreated{}
}

// WithPayload adds the payload to the post clusters Id preflights created response
func (o *PostClustersIDPreflightsCreated) WithPayload(payload *models.ResponseOperationPreflight) *PostClustersIDPreflightsCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post clusters Id preflights created response
func (o *PostClustersIDPreflightsCreated) SetPayload(payload *models.ResponseOperationPreflight) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostClustersIDPreflightsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostClustersIDPreflightsBadRequestCode is the HTTP code returned for type PostClustersIDPreflightsBadRequest
const PostClustersIDPreflightsBadRequestCode int = 400

// PostClustersIDPreflightsBadRequest Error
//
// swagger:response postClustersIdPreflightsBadRequest
type PostClustersIDPreflightsBadRequest struct {

	// In: Body
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewPostClustersIDPreflightsBadRequest creates PostClustersIDPreflightsBadRequest with default headers values
func NewPostClustersIDPreflightsBadRequest() *PostClustersIDPreflightsBadRequest {

	return &PostClustersIDPreflightsBadRequest{}
}

// WithPayload adds the payload to the post clusters Id preflights bad request response
func (o *PostClustersIDPreflightsBadRequest) WithPayload(payload *models.ResponseError) *PostClustersIDPreflightsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post clusters Id preflights bad request response
func (o *PostClustersIDPreflightsBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostClustersIDPreflightsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
