// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostClustersIDOperationsHandlerFunc turns a function with the right signature into a post clusters ID operations handler
type PostClustersIDOperationsHandlerFunc func(PostClustersIDOperationsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostClustersIDOperationsHandlerFunc) Handle(params PostClustersIDOperationsParams) middleware.Responder {
	return fn(params)
}

// PostClustersIDOperationsHandler interface for that can handle valid post clusters ID operations params
type PostClustersIDOperationsHandler interface {
	Handle(PostClustersIDOperationsParams) middleware.Responder
}

// NewPostClustersIDOperations creates a new http.Handler for the post clusters ID operations operation
func NewPostClustersIDOperations(ctx *middleware.Context, handler PostClustersIDOperationsHandler) *PostClustersIDOperations {
	return &PostClustersIDOperations{Context: ctx, Handler: handler}
}

// PostClustersIDOperations swagger:route POST /clusters/{id}/operations cluster postClustersIdOperations
//
// Launch a confirmed guarded cluster operation
type PostClustersIDOperations struct {
	Context *middleware.Context
	Handler PostClustersIDOperationsHandler
}

func (o *PostClustersIDOperations) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewPostClustersIDOperationsParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
