// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"postgresql-cluster-console/models"
)

// PostClustersIDOperationsAcceptedCode is the HTTP code returned for type PostClustersIDOperationsAccepted
const PostClustersIDOperationsAcceptedCode int = 202

// PostClustersIDOperationsAccepted Accepted
//
// swagger:response postClustersIdOperationsAccepted
type PostClustersIDOperationsAccepted struct {

	// In: Body
	Payload *models.ResponseOperationStart `json:"body,omitempty"`
}

// NewPostClustersIDOperationsAccepted creates PostClustersIDOperationsAccepted with default headers values
func NewPostClustersIDOperationsAccepted() *PostClustersIDOperationsAccepted {

	return &PostClustersIDOperationsAccepted{}
}

// WithPayload adds the payload to the post clusters Id operations accepted response
func (o *PostClustersIDOperationsAccepted) WithPayload(payload *models.ResponseOperationStart) *PostClustersIDOperationsAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post clusters Id operations accepted response
func (o *PostClustersIDOperationsAccepted) SetPayload(payload *models.ResponseOperationStart) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostClustersIDOperationsAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostClustersIDOperationsBadRequestCode is the HTTP code returned for type PostClustersIDOperationsBadRequest
const PostClustersIDOperationsBadRequestCode int = 400

// PostClustersIDOperationsBadRequest Error
//
// swagger:response postClustersIdOperationsBadRequest
type PostClustersIDOperationsBadRequest struct {

	// In: Body
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewPostClustersIDOperationsBadRequest creates PostClustersIDOperationsBadRequest with default headers values
func NewPostClustersIDOperationsBadRequest() *PostClustersIDOperationsBadRequest {

	return &PostClustersIDOperationsBadRequest{}
}

// WithPayload adds the payload to the post clusters Id operations bad request response
func (o *PostClustersIDOperationsBadRequest) WithPayload(payload *models.ResponseError) *PostClustersIDOperationsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post clusters Id operations bad request response
func (o *PostClustersIDOperationsBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostClustersIDOperationsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
