// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostClustersIDPreflightsHandlerFunc turns a function with the right signature into a post clusters ID preflights handler
type PostClustersIDPreflightsHandlerFunc func(PostClustersIDPreflightsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostClustersIDPreflightsHandlerFunc) Handle(params PostClustersIDPreflightsParams) middleware.Responder {
	return fn(params)
}

// PostClustersIDPreflightsHandler interface for that can handle valid post clusters ID preflights params
type PostClustersIDPreflightsHandler interface {
	Handle(PostClustersIDPreflightsParams) middleware.Responder
}

// NewPostClustersIDPreflights creates a new http.Handler for the post clusters ID preflights operation
func NewPostClustersIDPreflights(ctx *middleware.Context, handler PostClustersIDPreflightsHandler) *PostClustersIDPreflights {
	return &PostClustersIDPreflights{Context: ctx, Handler: handler}
}

// PostClustersIDPreflights swagger:route POST /clusters/{id}/preflights cluster postClustersIdPreflights
//
// Preflight a guarded cluster operation
type PostClustersIDPreflights struct {
	Context *middleware.Context
	Handler PostClustersIDPreflightsHandler
}

func (o *PostClustersIDPreflights) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewPostClustersIDPreflightsParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
