// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutClustersIDCredentialHandlerFunc turns a function with the right signature into a put clusters ID credential handler
type PutClustersIDCredentialHandlerFunc func(PutClustersIDCredentialParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutClustersIDCredentialHandlerFunc) Handle(params PutClustersIDCredentialParams) middleware.Responder {
	return fn(params)
}

// PutClustersIDCredentialHandler interface for that can handle valid put clusters ID credential params
type PutClustersIDCredentialHandler interface {
	Handle(PutClustersIDCredentialParams) middleware.Responder
}

// NewPutClustersIDCredential creates a new http.Handler for the put clusters ID credential operation
func NewPutClustersIDCredential(ctx *middleware.Context, handler PutClustersIDCredentialHandler) *PutClustersIDCredential {
	return &PutClustersIDCredential{Context: ctx, Handler: handler}
}

// PutClustersIDCredential swagger:route PUT /clusters/{id}/credential cluster putClustersIdCredential
//
// Attach management credential to cluster
type PutClustersIDCredential struct {
	Context *middleware.Context
	Handler PutClustersIDCredentialHandler
}

func (o *PutClustersIDCredential) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewPutClustersIDCredentialParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
