// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutClustersIDAutomationCredentialsHandlerFunc turns a function with the right signature into a put clusters ID automation credentials handler
type PutClustersIDAutomationCredentialsHandlerFunc func(PutClustersIDAutomationCredentialsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutClustersIDAutomationCredentialsHandlerFunc) Handle(params PutClustersIDAutomationCredentialsParams) middleware.Responder {
	return fn(params)
}

// PutClustersIDAutomationCredentialsHandler interface for that can handle valid put clusters ID automation credentials params
type PutClustersIDAutomationCredentialsHandler interface {
	Handle(PutClustersIDAutomationCredentialsParams) middleware.Responder
}

// NewPutClustersIDAutomationCredentials creates a new http.Handler for the put clusters ID automation credentials operation
func NewPutClustersIDAutomationCredentials(ctx *middleware.Context, handler PutClustersIDAutomationCredentialsHandler) *PutClustersIDAutomationCredentials {
	return &PutClustersIDAutomationCredentials{Context: ctx, Handler: handler}
}

// PutClustersIDAutomationCredentials swagger:route PUT /clusters/{id}/automation-credentials cluster putClustersIdAutomationCredentials
//
// Replace cluster automation credential bindings
type PutClustersIDAutomationCredentials struct {
	Context *middleware.Context
	Handler PutClustersIDAutomationCredentialsHandler
}

func (o *PutClustersIDAutomationCredentials) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewPutClustersIDAutomationCredentialsParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
