// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"postgresql-cluster-console/models"
)

// PutClustersIDAutomationCredentialsOKCode is the HTTP code returned for type PutClustersIDAutomationCredentialsOK
const PutClustersIDAutomationCredentialsOKCode int = 200

// PutClustersIDAutomationCredentialsOK OK
//
// swagger:response putClustersIdAutomationCredentialsOK
type PutClustersIDAutomationCredentialsOK struct {

	// In: Body
	Payload *models.ClusterInfo `json:"body,omitempty"`
}

// NewPutClustersIDAutomationCredentialsOK creates PutClustersIDAutomationCredentialsOK with default headers values
func NewPutClustersIDAutomationCredentialsOK() *PutClustersIDAutomationCredentialsOK {

	return &PutClustersIDAutomationCredentialsOK{}
}

// WithPayload adds the payload to the put clusters Id automation credentials o k response
func (o *PutClustersIDAutomationCredentialsOK) WithPayload(payload *models.ClusterInfo) *PutClustersIDAutomationCredentialsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put clusters Id automation credentials o k response
func (o *PutClustersIDAutomationCredentialsOK) SetPayload(payload *models.ClusterInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutClustersIDAutomationCredentialsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutClustersIDAutomationCredentialsBadRequestCode is the HTTP code returned for type PutClustersIDAutomationCredentialsBadRequest
const PutClustersIDAutomationCredentialsBadRequestCode int = 400

// PutClustersIDAutomationCredentialsBadRequest Error
//
// swagger:response putClustersIdAutomationCredentialsBadRequest
type PutClustersIDAutomationCredentialsBadRequest struct {

	// In: Body
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewPutClustersIDAutomationCredentialsBadRequest creates PutClustersIDAutomationCredentialsBadRequest with default headers values
func NewPutClustersIDAutomationCredentialsBadRequest() *PutClustersIDAutomationCredentialsBadRequest {

	return &PutClustersIDAutomationCredentialsBadRequest{}
}

// WithPayload adds the payload to the put clusters Id automation credentials bad request response
func (o *PutClustersIDAutomationCredentialsBadRequest) WithPayload(payload *models.ResponseError) *PutClustersIDAutomationCredentialsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put clusters Id automation credentials bad request response
func (o *PutClustersIDAutomationCredentialsBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutClustersIDAutomationCredentialsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
