// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"postgresql-cluster-console/models"
)

// PutClustersIDCredentialOKCode is the HTTP code returned for type PutClustersIDCredentialOK
const PutClustersIDCredentialOKCode int = 200

// PutClustersIDCredentialOK OK
//
// swagger:response putClustersIdCredentialOK
type PutClustersIDCredentialOK struct {

	// In: Body
	Payload *models.ClusterInfo `json:"body,omitempty"`
}

// NewPutClustersIDCredentialOK creates PutClustersIDCredentialOK with default headers values
func NewPutClustersIDCredentialOK() *PutClustersIDCredentialOK {

	return &PutClustersIDCredentialOK{}
}

// WithPayload adds the payload to the put clusters Id credential o k response
func (o *PutClustersIDCredentialOK) WithPayload(payload *models.ClusterInfo) *PutClustersIDCredentialOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put clusters Id credential o k response
func (o *PutClustersIDCredentialOK) SetPayload(payload *models.ClusterInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutClustersIDCredentialOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutClustersIDCredentialBadRequestCode is the HTTP code returned for type PutClustersIDCredentialBadRequest
const PutClustersIDCredentialBadRequestCode int = 400

// PutClustersIDCredentialBadRequest Error
//
// swagger:response putClustersIdCredentialBadRequest
type PutClustersIDCredentialBadRequest struct {

	// In: Body
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewPutClustersIDCredentialBadRequest creates PutClustersIDCredentialBadRequest with default headers values
func NewPutClustersIDCredentialBadRequest() *PutClustersIDCredentialBadRequest {

	return &PutClustersIDCredentialBadRequest{}
}

// WithPayload adds the payload to the put clusters Id credential bad request response
func (o *PutClustersIDCredentialBadRequest) WithPayload(payload *models.ResponseError) *PutClustersIDCredentialBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put clusters Id credential bad request response
func (o *PutClustersIDCredentialBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutClustersIDCredentialBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
