// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// ClusterInfoAutomationCredentials cluster info automation credentials
//
// swagger:model ClusterInfo.AutomationCredentials
type ClusterInfoAutomationCredentials struct {

	// patroni restapi secret id
	PatroniRestapiSecretID *int64 `json:"patroni_restapi_secret_id,omitempty"`

	// postgres replication secret id
	PostgresReplicationSecretID *int64 `json:"postgres_replication_secret_id,omitempty"`

	// postgres superuser secret id
	PostgresSuperuserSecretID *int64 `json:"postgres_superuser_secret_id,omitempty"`
}

// Validate validates this cluster info automation credentials
func (m *ClusterInfoAutomationCredentials) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cluster info automation credentials based on context it is used
func (m *ClusterInfoAutomationCredentials) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterInfoAutomationCredentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterInfoAutomationCredentials) UnmarshalBinary(b []byte) error {
	var res ClusterInfoAutomationCredentials
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
