// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// ClusterInfoInstance Instance info for current cluster
//
// swagger:model ClusterInfo.Instance
type ClusterInfoInstance struct {

	// id
	ID int64 `json:"id,omitempty"`

	// ip
	// Example: 10.128.64.141
	IP string `json:"ip,omitempty"`

	// lag
	// Example: 0
	Lag *int64 `json:"lag,omitempty"`

	// name
	// Example: pgnode1
	Name string `json:"name,omitempty"`

	// pending restart
	// Example: false
	PendingRestart *bool `json:"pending_restart,omitempty"`

	// role
	// Example: leader
	Role string `json:"role,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// tags
	Tags any `json:"tags,omitempty"`

	// timeline
	// Example: 1
	Timeline *int64 `json:"timeline,omitempty"`
}

// Validate validates this cluster info instance
func (m *ClusterInfoInstance) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cluster info instance based on context it is used
func (m *ClusterInfoInstance) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterInfoInstance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterInfoInstance) UnmarshalBinary(b []byte) error {
	var res ClusterInfoInstance
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
