// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// HealthOperationSummary health operation summary
//
// swagger:model Health.OperationSummary
type HealthOperationSummary struct {

	// active
	Active *HealthOperation `json:"active,omitempty"`

	// latest
	Latest *HealthOperation `json:"latest,omitempty"`

	// unresolved
	Unresolved *HealthOperation `json:"unresolved,omitempty"`
}

// Validate validates this health operation summary
func (m *HealthOperationSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActive(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLatest(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUnresolved(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HealthOperationSummary) validateActive(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Active) { // not required
		return nil
	}

	if m.Active != nil {
		if err := m.Active.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("active")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("active")
			}

			return err
		}
	}

	return nil
}

func (m *HealthOperationSummary) validateLatest(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Latest) { // not required
		return nil
	}

	if m.Latest != nil {
		if err := m.Latest.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("latest")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("latest")
			}

			return err
		}
	}

	return nil
}

func (m *HealthOperationSummary) validateUnresolved(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Unresolved) { // not required
		return nil
	}

	if m.Unresolved != nil {
		if err := m.Unresolved.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("unresolved")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("unresolved")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this health operation summary based on the context it is used
func (m *HealthOperationSummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateActive(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLatest(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUnresolved(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HealthOperationSummary) contextValidateActive(ctx context.Context, formats strfmt.Registry) error {

	if m.Active != nil {

		if typeutils.IsZero(m.Active) { // not required
			return nil
		}

		if err := m.Active.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("active")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("active")
			}

			return err
		}
	}

	return nil
}

func (m *HealthOperationSummary) contextValidateLatest(ctx context.Context, formats strfmt.Registry) error {

	if m.Latest != nil {

		if typeutils.IsZero(m.Latest) { // not required
			return nil
		}

		if err := m.Latest.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("latest")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("latest")
			}

			return err
		}
	}

	return nil
}

func (m *HealthOperationSummary) contextValidateUnresolved(ctx context.Context, formats strfmt.Registry) error {

	if m.Unresolved != nil {

		if typeutils.IsZero(m.Unresolved) { // not required
			return nil
		}

		if err := m.Unresolved.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("unresolved")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("unresolved")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HealthOperationSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HealthOperationSummary) UnmarshalBinary(b []byte) error {
	var res HealthOperationSummary
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
