// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HealthRoutingTarget health routing target
//
// swagger:model Health.RoutingTarget
type HealthRoutingTarget struct {

	// address
	Address string `json:"address,omitempty"`

	// port
	Port *int64 `json:"port,omitempty"`

	// reachable
	Reachable *bool `json:"reachable,omitempty"`

	// role
	Role string `json:"role,omitempty"`

	// role matches
	RoleMatches *bool `json:"role_matches,omitempty"`
}

// Validate validates this health routing target
func (m *HealthRoutingTarget) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this health routing target based on context it is used
func (m *HealthRoutingTarget) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HealthRoutingTarget) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HealthRoutingTarget) UnmarshalBinary(b []byte) error {
	var res HealthRoutingTarget
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
