// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// HealthRecoverability health recoverability
//
// swagger:model Health.Recoverability
type HealthRecoverability struct {

	// reasons
	Reasons []string `json:"reasons"`

	// state
	// Enum: ["healthy","degraded"]
	State string `json:"state,omitempty"`
}

// Validate validates this health recoverability
func (m *HealthRecoverability) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var healthRecoverabilityTypeStatePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["healthy","degraded"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		healthRecoverabilityTypeStatePropEnum = append(healthRecoverabilityTypeStatePropEnum, v)
	}
}

const (

	// HealthRecoverabilityStateHealthy captures enum value "healthy"
	HealthRecoverabilityStateHealthy string = "healthy"

	// HealthRecoverabilityStateDegraded captures enum value "degraded"
	HealthRecoverabilityStateDegraded string = "degraded"
)

// prop value enum
func (m *HealthRecoverability) validateStateEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, healthRecoverabilityTypeStatePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *HealthRecoverability) validateState(formats strfmt.Registry) error {
	if typeutils.IsZero(m.State) { // not required
		return nil
	}

	// value enum
	if err := m.validateStateEnum("state", "body", m.State); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this health recoverability based on context it is used
func (m *HealthRecoverability) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HealthRecoverability) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HealthRecoverability) UnmarshalBinary(b []byte) error {
	var res HealthRecoverability
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
