// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HealthDCS health d c s
//
// swagger:model Health.DCS
type HealthDCS struct {

	// members
	Members []string `json:"members"`

	// reachable
	Reachable *bool `json:"reachable,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this health d c s
func (m *HealthDCS) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this health d c s based on context it is used
func (m *HealthDCS) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HealthDCS) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HealthDCS) UnmarshalBinary(b []byte) error {
	var res HealthDCS
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
