// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// HealthBackup health backup
//
// swagger:model Health.Backup
type HealthBackup struct {

	// fresh
	Fresh *bool `json:"fresh,omitempty"`

	// freshness policy
	FreshnessPolicy *string `json:"freshness_policy,omitempty"`

	// latest differential
	// Format: date-time
	LatestDifferential *strfmt.DateTime `json:"latest_differential,omitempty"`

	// latest full
	// Format: date-time
	LatestFull *strfmt.DateTime `json:"latest_full,omitempty"`

	// locks
	Locks []string `json:"locks"`

	// repository reachable
	RepositoryReachable *bool `json:"repository_reachable,omitempty"`

	// restore tested at
	// Format: date-time
	RestoreTestedAt *strfmt.DateTime `json:"restore_tested_at,omitempty"`

	// retention
	Retention any `json:"retention,omitempty"`

	// scheduler owner
	SchedulerOwner *string `json:"scheduler_owner,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// wal continuous
	WalContinuous *bool `json:"wal_continuous,omitempty"`
}

// Validate validates this health backup
func (m *HealthBackup) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLatestDifferential(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLatestFull(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRestoreTestedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HealthBackup) validateLatestDifferential(formats strfmt.Registry) error {
	if typeutils.IsZero(m.LatestDifferential) { // not required
		return nil
	}

	if err := validate.FormatOf("latest_differential", "body", "date-time", m.LatestDifferential.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *HealthBackup) validateLatestFull(formats strfmt.Registry) error {
	if typeutils.IsZero(m.LatestFull) { // not required
		return nil
	}

	if err := validate.FormatOf("latest_full", "body", "date-time", m.LatestFull.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *HealthBackup) validateRestoreTestedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.RestoreTestedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("restore_tested_at", "body", "date-time", m.RestoreTestedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this health backup based on context it is used
func (m *HealthBackup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HealthBackup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HealthBackup) UnmarshalBinary(b []byte) error {
	var res HealthBackup
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
