// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HealthMember health member
//
// swagger:model Health.Member
type HealthMember struct {

	// lag
	Lag *int64 `json:"lag,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// pending restart
	PendingRestart *bool `json:"pending_restart,omitempty"`

	// role
	Role string `json:"role,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// timeline
	Timeline *int64 `json:"timeline,omitempty"`
}

// Validate validates this health member
func (m *HealthMember) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this health member based on context it is used
func (m *HealthMember) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HealthMember) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HealthMember) UnmarshalBinary(b []byte) error {
	var res HealthMember
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
