// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// HealthTopology health topology
//
// swagger:model Health.Topology
type HealthTopology struct {

	// leader
	Leader *HealthMember `json:"leader,omitempty"`

	// members
	Members []*HealthMember `json:"members"`

	// observed at
	// Format: date-time
	ObservedAt *strfmt.DateTime `json:"observed_at,omitempty"`

	// patroni reachable
	PatroniReachable *bool `json:"patroni_reachable,omitempty"`

	// replicas
	Replicas []*HealthMember `json:"replicas"`

	// state
	State string `json:"state,omitempty"`
}

// Validate validates this health topology
func (m *HealthTopology) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLeader(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMembers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateObservedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReplicas(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HealthTopology) validateLeader(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Leader) { // not required
		return nil
	}

	if m.Leader != nil {
		if err := m.Leader.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("leader")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("leader")
			}

			return err
		}
	}

	return nil
}

func (m *HealthTopology) validateMembers(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Members) { // not required
		return nil
	}

	for i := 0; i < len(m.Members); i++ {
		if typeutils.IsZero(m.Members[i]) { // not required
			continue
		}

		if m.Members[i] != nil {
			if err := m.Members[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("members" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("members" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *HealthTopology) validateObservedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ObservedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("observed_at", "body", "date-time", m.ObservedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *HealthTopology) validateReplicas(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Replicas) { // not required
		return nil
	}

	for i := 0; i < len(m.Replicas); i++ {
		if typeutils.IsZero(m.Replicas[i]) { // not required
			continue
		}

		if m.Replicas[i] != nil {
			if err := m.Replicas[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("replicas" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("replicas" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this health topology based on the context it is used
func (m *HealthTopology) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLeader(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMembers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReplicas(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HealthTopology) contextValidateLeader(ctx context.Context, formats strfmt.Registry) error {

	if m.Leader != nil {

		if typeutils.IsZero(m.Leader) { // not required
			return nil
		}

		if err := m.Leader.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("leader")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("leader")
			}

			return err
		}
	}

	return nil
}

func (m *HealthTopology) contextValidateMembers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Members); i++ {

		if m.Members[i] != nil {

			if typeutils.IsZero(m.Members[i]) { // not required
				return nil
			}

			if err := m.Members[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("members" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("members" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *HealthTopology) contextValidateReplicas(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Replicas); i++ {

		if m.Replicas[i] != nil {

			if typeutils.IsZero(m.Replicas[i]) { // not required
				return nil
			}

			if err := m.Replicas[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("replicas" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("replicas" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HealthTopology) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HealthTopology) UnmarshalBinary(b []byte) error {
	var res HealthTopology
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
