// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// QueryPerformanceQuery query performance query
//
// swagger:model QueryPerformance.Query
type QueryPerformanceQuery struct {

	// fingerprint id
	FingerprintID string `json:"fingerprint_id,omitempty"`

	// metrics
	Metrics *QueryPerformanceMetrics `json:"metrics,omitempty"`

	// normalized query
	NormalizedQuery string `json:"normalized_query,omitempty"`

	// top max latency
	TopMaxLatency bool `json:"top_max_latency,omitempty"`

	// top total time
	TopTotalTime bool `json:"top_total_time,omitempty"`
}

// Validate validates this query performance query
func (m *QueryPerformanceQuery) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetrics(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QueryPerformanceQuery) validateMetrics(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Metrics) { // not required
		return nil
	}

	if m.Metrics != nil {
		if err := m.Metrics.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("metrics")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("metrics")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this query performance query based on the context it is used
func (m *QueryPerformanceQuery) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetrics(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QueryPerformanceQuery) contextValidateMetrics(ctx context.Context, formats strfmt.Registry) error {

	if m.Metrics != nil {

		if typeutils.IsZero(m.Metrics) { // not required
			return nil
		}

		if err := m.Metrics.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("metrics")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("metrics")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *QueryPerformanceQuery) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryPerformanceQuery) UnmarshalBinary(b []byte) error {
	var res QueryPerformanceQuery
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
