// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// QueryPerformanceFilters query performance filters
//
// swagger:model QueryPerformance.Filters
type QueryPerformanceFilters struct {

	// applications
	Applications []string `json:"applications"`

	// databases
	Databases []string `json:"databases"`

	// roles
	Roles []string `json:"roles"`
}

// Validate validates this query performance filters
func (m *QueryPerformanceFilters) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this query performance filters based on context it is used
func (m *QueryPerformanceFilters) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QueryPerformanceFilters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryPerformanceFilters) UnmarshalBinary(b []byte) error {
	var res QueryPerformanceFilters
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
