// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// QueryPerformancePoint query performance point
//
// swagger:model QueryPerformance.Point
type QueryPerformancePoint struct {

	// bucket start
	// Format: date-time
	BucketStart strfmt.DateTime `json:"bucket_start,omitempty"`

	// metrics
	Metrics *QueryPerformanceMetrics `json:"metrics,omitempty"`
}

// Validate validates this query performance point
func (m *QueryPerformancePoint) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBucketStart(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetrics(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QueryPerformancePoint) validateBucketStart(formats strfmt.Registry) error {
	if typeutils.IsZero(m.BucketStart) { // not required
		return nil
	}

	if err := validate.FormatOf("bucket_start", "body", "date-time", m.BucketStart.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *QueryPerformancePoint) validateMetrics(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Metrics) { // not required
		return nil
	}

	if m.Metrics != nil {
		if err := m.Metrics.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("metrics")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("metrics")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this query performance point based on the context it is used
func (m *QueryPerformancePoint) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetrics(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QueryPerformancePoint) contextValidateMetrics(ctx context.Context, formats strfmt.Registry) error {

	if m.Metrics != nil {

		if typeutils.IsZero(m.Metrics) { // not required
			return nil
		}

		if err := m.Metrics.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("metrics")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("metrics")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *QueryPerformancePoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryPerformancePoint) UnmarshalBinary(b []byte) error {
	var res QueryPerformancePoint
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
