// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// QueryPerformanceCoverage query performance coverage
//
// swagger:model QueryPerformance.Coverage
type QueryPerformanceCoverage struct {

	// collection status
	CollectionStatus string `json:"collection_status,omitempty"`

	// extension version
	ExtensionVersion *string `json:"extension_version,omitempty"`

	// last bucket start
	// Format: date-time
	LastBucketStart *strfmt.DateTime `json:"last_bucket_start,omitempty"`

	// last collected at
	// Format: date-time
	LastCollectedAt *strfmt.DateTime `json:"last_collected_at,omitempty"`

	// last error code
	LastErrorCode *string `json:"last_error_code,omitempty"`

	// server id
	ServerID int64 `json:"server_id,omitempty"`

	// server name
	ServerName string `json:"server_name,omitempty"`

	// server role
	ServerRole string `json:"server_role,omitempty"`

	// server status
	ServerStatus string `json:"server_status,omitempty"`
}

// Validate validates this query performance coverage
func (m *QueryPerformanceCoverage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastBucketStart(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastCollectedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QueryPerformanceCoverage) validateLastBucketStart(formats strfmt.Registry) error {
	if typeutils.IsZero(m.LastBucketStart) { // not required
		return nil
	}

	if err := validate.FormatOf("last_bucket_start", "body", "date-time", m.LastBucketStart.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *QueryPerformanceCoverage) validateLastCollectedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.LastCollectedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("last_collected_at", "body", "date-time", m.LastCollectedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this query performance coverage based on context it is used
func (m *QueryPerformanceCoverage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QueryPerformanceCoverage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryPerformanceCoverage) UnmarshalBinary(b []byte) error {
	var res QueryPerformanceCoverage
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
