// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// QueryPerformanceMetrics query performance metrics
//
// swagger:model QueryPerformance.Metrics
type QueryPerformanceMetrics struct {

	// calls
	Calls int64 `json:"calls,omitempty"`

	// max exec time ms
	MaxExecTimeMs float64 `json:"max_exec_time_ms,omitempty"`

	// mean exec time ms
	MeanExecTimeMs float64 `json:"mean_exec_time_ms,omitempty"`

	// read time ms
	ReadTimeMs float64 `json:"read_time_ms,omitempty"`

	// rows
	Rows int64 `json:"rows,omitempty"`

	// shared blocks hit
	SharedBlocksHit int64 `json:"shared_blocks_hit,omitempty"`

	// shared blocks read
	SharedBlocksRead int64 `json:"shared_blocks_read,omitempty"`

	// temp blocks read
	TempBlocksRead int64 `json:"temp_blocks_read,omitempty"`

	// temp blocks written
	TempBlocksWritten int64 `json:"temp_blocks_written,omitempty"`

	// total exec time ms
	TotalExecTimeMs float64 `json:"total_exec_time_ms,omitempty"`

	// wal bytes
	WalBytes int64 `json:"wal_bytes,omitempty"`

	// write time ms
	WriteTimeMs float64 `json:"write_time_ms,omitempty"`
}

// Validate validates this query performance metrics
func (m *QueryPerformanceMetrics) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this query performance metrics based on context it is used
func (m *QueryPerformanceMetrics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QueryPerformanceMetrics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryPerformanceMetrics) UnmarshalBinary(b []byte) error {
	var res QueryPerformanceMetrics
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
