// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// QueryPerformanceStatus query performance status
//
// swagger:model QueryPerformance.Status
type QueryPerformanceStatus struct {

	// collected node count
	CollectedNodeCount int64 `json:"collected_node_count,omitempty"`

	// desired
	Desired bool `json:"desired,omitempty"`

	// expected node count
	ExpectedNodeCount int64 `json:"expected_node_count,omitempty"`

	// managed
	Managed bool `json:"managed,omitempty"`

	// postgres version
	PostgresVersion int64 `json:"postgres_version,omitempty"`

	// state
	// Enum: ["unsupported","rollout_required","disabled","collecting","enabled","degraded"]
	State string `json:"state,omitempty"`
}

// Validate validates this query performance status
func (m *QueryPerformanceStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var queryPerformanceStatusTypeStatePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["unsupported","rollout_required","disabled","collecting","enabled","degraded"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		queryPerformanceStatusTypeStatePropEnum = append(queryPerformanceStatusTypeStatePropEnum, v)
	}
}

const (

	// QueryPerformanceStatusStateUnsupported captures enum value "unsupported"
	QueryPerformanceStatusStateUnsupported string = "unsupported"

	// QueryPerformanceStatusStateRolloutRequired captures enum value "rollout_required"
	QueryPerformanceStatusStateRolloutRequired string = "rollout_required"

	// QueryPerformanceStatusStateDisabled captures enum value "disabled"
	QueryPerformanceStatusStateDisabled string = "disabled"

	// QueryPerformanceStatusStateCollecting captures enum value "collecting"
	QueryPerformanceStatusStateCollecting string = "collecting"

	// QueryPerformanceStatusStateEnabled captures enum value "enabled"
	QueryPerformanceStatusStateEnabled string = "enabled"

	// QueryPerformanceStatusStateDegraded captures enum value "degraded"
	QueryPerformanceStatusStateDegraded string = "degraded"
)

// prop value enum
func (m *QueryPerformanceStatus) validateStateEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, queryPerformanceStatusTypeStatePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *QueryPerformanceStatus) validateState(formats strfmt.Registry) error {
	if typeutils.IsZero(m.State) { // not required
		return nil
	}

	// value enum
	if err := m.validateStateEnum("state", "body", m.State); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this query performance status based on context it is used
func (m *QueryPerformanceStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QueryPerformanceStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryPerformanceStatus) UnmarshalBinary(b []byte) error {
	var res QueryPerformanceStatus
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
