// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// RequestChangeSetting Change setting
//
// swagger:model Request.ChangeSetting
type RequestChangeSetting struct {

	// value
	Value any `json:"value,omitempty"`
}

// Validate validates this request change setting
func (m *RequestChangeSetting) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request change setting based on context it is used
func (m *RequestChangeSetting) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestChangeSetting) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestChangeSetting) UnmarshalBinary(b []byte) error {
	var res RequestChangeSetting
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
