// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// RequestSecretValueGcp request secret value gcp
//
// swagger:model Request.SecretValue.Gcp
type RequestSecretValueGcp struct {

	// g c p s e r v i c e a c c o u n t c o n t e n t s
	GCPSERVICEACCOUNTCONTENTS string `json:"GCP_SERVICE_ACCOUNT_CONTENTS,omitempty"`
}

// Validate validates this request secret value gcp
func (m *RequestSecretValueGcp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request secret value gcp based on context it is used
func (m *RequestSecretValueGcp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestSecretValueGcp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestSecretValueGcp) UnmarshalBinary(b []byte) error {
	var res RequestSecretValueGcp
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
