// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// RequestClusterRoutingTarget request cluster routing target
//
// swagger:model Request.ClusterRoutingTarget
type RequestClusterRoutingTarget struct {

	// addresses
	// Required: true
	// Min Items: 1
	Addresses []string `json:"addresses"`

	// port
	// Required: true
	// Maximum: 65535
	// Minimum: 1
	Port *int64 `json:"port"`
}

// Validate validates this request cluster routing target
func (m *RequestClusterRoutingTarget) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddresses(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePort(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequestClusterRoutingTarget) validateAddresses(formats strfmt.Registry) error {

	if err := validate.Required("addresses", "body", m.Addresses); err != nil {
		return err
	}

	iAddressesSize := int64(len(m.Addresses))

	if err := validate.MinItems("addresses", "body", iAddressesSize, 1); err != nil {
		return err
	}

	return nil
}

func (m *RequestClusterRoutingTarget) validatePort(formats strfmt.Registry) error {

	if err := validate.Required("port", "body", m.Port); err != nil {
		return err
	}

	if err := validate.MinimumInt("port", "body", *m.Port, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("port", "body", *m.Port, 65535, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this request cluster routing target based on context it is used
func (m *RequestClusterRoutingTarget) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestClusterRoutingTarget) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestClusterRoutingTarget) UnmarshalBinary(b []byte) error {
	var res RequestClusterRoutingTarget
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
