// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// RequestOperationPreflight request operation preflight
//
// swagger:model Request.OperationPreflight
type RequestOperationPreflight struct {

	// params
	Params *RequestOperationParams `json:"params,omitempty"`

	// target
	Target string `json:"target,omitempty"`

	// type
	// Required: true
	// Enum: ["switchover","reload","rolling_restart","replica_reinit","backup_full","backup_diff","query_analytics_enable","query_analytics_disable","node_add","node_remove","config_update","rolling_update","postgresql_upgrade","emergency_failover","restore","pitr","database_admin","extension_admin","pgbouncer_admin"]
	Type *string `json:"type"`
}

// Validate validates this request operation preflight
func (m *RequestOperationPreflight) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParams(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequestOperationPreflight) validateParams(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Params) { // not required
		return nil
	}

	if m.Params != nil {
		if err := m.Params.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("params")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("params")
			}

			return err
		}
	}

	return nil
}

var requestOperationPreflightTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["switchover","reload","rolling_restart","replica_reinit","backup_full","backup_diff","query_analytics_enable","query_analytics_disable","node_add","node_remove","config_update","rolling_update","postgresql_upgrade","emergency_failover","restore","pitr","database_admin","extension_admin","pgbouncer_admin"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		requestOperationPreflightTypeTypePropEnum = append(requestOperationPreflightTypeTypePropEnum, v)
	}
}

const (

	// RequestOperationPreflightTypeSwitchover captures enum value "switchover"
	RequestOperationPreflightTypeSwitchover string = "switchover"

	// RequestOperationPreflightTypeReload captures enum value "reload"
	RequestOperationPreflightTypeReload string = "reload"

	// RequestOperationPreflightTypeRollingRestart captures enum value "rolling_restart"
	RequestOperationPreflightTypeRollingRestart string = "rolling_restart"

	// RequestOperationPreflightTypeReplicaReinit captures enum value "replica_reinit"
	RequestOperationPreflightTypeReplicaReinit string = "replica_reinit"

	// RequestOperationPreflightTypeBackupFull captures enum value "backup_full"
	RequestOperationPreflightTypeBackupFull string = "backup_full"

	// RequestOperationPreflightTypeBackupDiff captures enum value "backup_diff"
	RequestOperationPreflightTypeBackupDiff string = "backup_diff"

	// RequestOperationPreflightTypeQueryAnalyticsEnable captures enum value "query_analytics_enable"
	RequestOperationPreflightTypeQueryAnalyticsEnable string = "query_analytics_enable"

	// RequestOperationPreflightTypeQueryAnalyticsDisable captures enum value "query_analytics_disable"
	RequestOperationPreflightTypeQueryAnalyticsDisable string = "query_analytics_disable"

	// RequestOperationPreflightTypeNodeAdd captures enum value "node_add"
	RequestOperationPreflightTypeNodeAdd string = "node_add"

	// RequestOperationPreflightTypeNodeRemove captures enum value "node_remove"
	RequestOperationPreflightTypeNodeRemove string = "node_remove"

	// RequestOperationPreflightTypeConfigUpdate captures enum value "config_update"
	RequestOperationPreflightTypeConfigUpdate string = "config_update"

	// RequestOperationPreflightTypeRollingUpdate captures enum value "rolling_update"
	RequestOperationPreflightTypeRollingUpdate string = "rolling_update"

	// RequestOperationPreflightTypePostgresqlUpgrade captures enum value "postgresql_upgrade"
	RequestOperationPreflightTypePostgresqlUpgrade string = "postgresql_upgrade"

	// RequestOperationPreflightTypeEmergencyFailover captures enum value "emergency_failover"
	RequestOperationPreflightTypeEmergencyFailover string = "emergency_failover"

	// RequestOperationPreflightTypeRestore captures enum value "restore"
	RequestOperationPreflightTypeRestore string = "restore"

	// RequestOperationPreflightTypePitr captures enum value "pitr"
	RequestOperationPreflightTypePitr string = "pitr"

	// RequestOperationPreflightTypeDatabaseAdmin captures enum value "database_admin"
	RequestOperationPreflightTypeDatabaseAdmin string = "database_admin"

	// RequestOperationPreflightTypeExtensionAdmin captures enum value "extension_admin"
	RequestOperationPreflightTypeExtensionAdmin string = "extension_admin"

	// RequestOperationPreflightTypePgbouncerAdmin captures enum value "pgbouncer_admin"
	RequestOperationPreflightTypePgbouncerAdmin string = "pgbouncer_admin"
)

// prop value enum
func (m *RequestOperationPreflight) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, requestOperationPreflightTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RequestOperationPreflight) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this request operation preflight based on the context it is used
func (m *RequestOperationPreflight) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateParams(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequestOperationPreflight) contextValidateParams(ctx context.Context, formats strfmt.Registry) error {

	if m.Params != nil {

		if typeutils.IsZero(m.Params) { // not required
			return nil
		}

		if err := m.Params.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("params")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("params")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RequestOperationPreflight) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestOperationPreflight) UnmarshalBinary(b []byte) error {
	var res RequestOperationPreflight
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
