// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// RequestPostgreSQLParameter request postgre SQL parameter
//
// swagger:model Request.PostgreSQLParameter
type RequestPostgreSQLParameter struct {

	// option
	// Required: true
	// Enum: ["autovacuum_analyze_scale_factor","autovacuum_vacuum_scale_factor","deadlock_timeout","default_statistics_target","effective_cache_size","idle_in_transaction_session_timeout","log_checkpoints","log_connections","log_disconnections","log_lock_waits","log_min_duration_statement","log_statement","lock_timeout","maintenance_work_mem","random_page_cost","seq_page_cost","statement_timeout","work_mem"]
	Option *string `json:"option"`

	// value
	// Required: true
	// Min Length: 1
	Value *string `json:"value"`
}

// Validate validates this request postgre SQL parameter
func (m *RequestPostgreSQLParameter) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOption(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var requestPostgreSqlParameterTypeOptionPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["autovacuum_analyze_scale_factor","autovacuum_vacuum_scale_factor","deadlock_timeout","default_statistics_target","effective_cache_size","idle_in_transaction_session_timeout","log_checkpoints","log_connections","log_disconnections","log_lock_waits","log_min_duration_statement","log_statement","lock_timeout","maintenance_work_mem","random_page_cost","seq_page_cost","statement_timeout","work_mem"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		requestPostgreSqlParameterTypeOptionPropEnum = append(requestPostgreSqlParameterTypeOptionPropEnum, v)
	}
}

const (

	// RequestPostgreSQLParameterOptionAutovacuumAnalyzeScaleFactor captures enum value "autovacuum_analyze_scale_factor"
	RequestPostgreSQLParameterOptionAutovacuumAnalyzeScaleFactor string = "autovacuum_analyze_scale_factor"

	// RequestPostgreSQLParameterOptionAutovacuumVacuumScaleFactor captures enum value "autovacuum_vacuum_scale_factor"
	RequestPostgreSQLParameterOptionAutovacuumVacuumScaleFactor string = "autovacuum_vacuum_scale_factor"

	// RequestPostgreSQLParameterOptionDeadlockTimeout captures enum value "deadlock_timeout"
	RequestPostgreSQLParameterOptionDeadlockTimeout string = "deadlock_timeout"

	// RequestPostgreSQLParameterOptionDefaultStatisticsTarget captures enum value "default_statistics_target"
	RequestPostgreSQLParameterOptionDefaultStatisticsTarget string = "default_statistics_target"

	// RequestPostgreSQLParameterOptionEffectiveCacheSize captures enum value "effective_cache_size"
	RequestPostgreSQLParameterOptionEffectiveCacheSize string = "effective_cache_size"

	// RequestPostgreSQLParameterOptionIdleInTransactionSessionTimeout captures enum value "idle_in_transaction_session_timeout"
	RequestPostgreSQLParameterOptionIdleInTransactionSessionTimeout string = "idle_in_transaction_session_timeout"

	// RequestPostgreSQLParameterOptionLogCheckpoints captures enum value "log_checkpoints"
	RequestPostgreSQLParameterOptionLogCheckpoints string = "log_checkpoints"

	// RequestPostgreSQLParameterOptionLogConnections captures enum value "log_connections"
	RequestPostgreSQLParameterOptionLogConnections string = "log_connections"

	// RequestPostgreSQLParameterOptionLogDisconnections captures enum value "log_disconnections"
	RequestPostgreSQLParameterOptionLogDisconnections string = "log_disconnections"

	// RequestPostgreSQLParameterOptionLogLockWaits captures enum value "log_lock_waits"
	RequestPostgreSQLParameterOptionLogLockWaits string = "log_lock_waits"

	// RequestPostgreSQLParameterOptionLogMinDurationStatement captures enum value "log_min_duration_statement"
	RequestPostgreSQLParameterOptionLogMinDurationStatement string = "log_min_duration_statement"

	// RequestPostgreSQLParameterOptionLogStatement captures enum value "log_statement"
	RequestPostgreSQLParameterOptionLogStatement string = "log_statement"

	// RequestPostgreSQLParameterOptionLockTimeout captures enum value "lock_timeout"
	RequestPostgreSQLParameterOptionLockTimeout string = "lock_timeout"

	// RequestPostgreSQLParameterOptionMaintenanceWorkMem captures enum value "maintenance_work_mem"
	RequestPostgreSQLParameterOptionMaintenanceWorkMem string = "maintenance_work_mem"

	// RequestPostgreSQLParameterOptionRandomPageCost captures enum value "random_page_cost"
	RequestPostgreSQLParameterOptionRandomPageCost string = "random_page_cost"

	// RequestPostgreSQLParameterOptionSeqPageCost captures enum value "seq_page_cost"
	RequestPostgreSQLParameterOptionSeqPageCost string = "seq_page_cost"

	// RequestPostgreSQLParameterOptionStatementTimeout captures enum value "statement_timeout"
	RequestPostgreSQLParameterOptionStatementTimeout string = "statement_timeout"

	// RequestPostgreSQLParameterOptionWorkMem captures enum value "work_mem"
	RequestPostgreSQLParameterOptionWorkMem string = "work_mem"
)

// prop value enum
func (m *RequestPostgreSQLParameter) validateOptionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, requestPostgreSqlParameterTypeOptionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RequestPostgreSQLParameter) validateOption(formats strfmt.Registry) error {

	if err := validate.Required("option", "body", m.Option); err != nil {
		return err
	}

	// value enum
	if err := m.validateOptionEnum("option", "body", *m.Option); err != nil {
		return err
	}

	return nil
}

func (m *RequestPostgreSQLParameter) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	if err := validate.MinLength("value", "body", *m.Value, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this request postgre SQL parameter based on context it is used
func (m *RequestPostgreSQLParameter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestPostgreSQLParameter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestPostgreSQLParameter) UnmarshalBinary(b []byte) error {
	var res RequestPostgreSQLParameter
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
