// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// RequestProjectCreate request project create
//
// swagger:model Request.ProjectCreate
type RequestProjectCreate struct {

	// description
	// Example: Default project
	Description string `json:"description,omitempty"`

	// name
	// Example: default
	Name string `json:"name,omitempty"`
}

// Validate validates this request project create
func (m *RequestProjectCreate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request project create based on context it is used
func (m *RequestProjectCreate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestProjectCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestProjectCreate) UnmarshalBinary(b []byte) error {
	var res RequestProjectCreate
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
