// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// RequestSecretValueHetzner request secret value hetzner
//
// swagger:model Request.SecretValue.Hetzner
type RequestSecretValueHetzner struct {

	// h c l o u d API t o k e n
	HCLOUDAPITOKEN string `json:"HCLOUD_API_TOKEN,omitempty"`
}

// Validate validates this request secret value hetzner
func (m *RequestSecretValueHetzner) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request secret value hetzner based on context it is used
func (m *RequestSecretValueHetzner) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestSecretValueHetzner) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestSecretValueHetzner) UnmarshalBinary(b []byte) error {
	var res RequestSecretValueHetzner
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
