// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// RequestClusterCredential request cluster credential
//
// swagger:model Request.ClusterCredential
type RequestClusterCredential struct {

	// secret id
	// Required: true
	SecretID *int64 `json:"secret_id"`
}

// Validate validates this request cluster credential
func (m *RequestClusterCredential) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSecretID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequestClusterCredential) validateSecretID(formats strfmt.Registry) error {

	if err := validate.Required("secret_id", "body", m.SecretID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this request cluster credential based on context it is used
func (m *RequestClusterCredential) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestClusterCredential) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestClusterCredential) UnmarshalBinary(b []byte) error {
	var res RequestClusterCredential
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
