// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// RequestCreateSetting Create new setting
//
// swagger:model Request.CreateSetting
type RequestCreateSetting struct {

	// name
	Name string `json:"name,omitempty"`

	// value
	Value any `json:"value,omitempty"`
}

// Validate validates this request create setting
func (m *RequestCreateSetting) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request create setting based on context it is used
func (m *RequestCreateSetting) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestCreateSetting) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestCreateSetting) UnmarshalBinary(b []byte) error {
	var res RequestCreateSetting
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
