// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// RequestSecretValueSSHKey request secret value Ssh key
//
// swagger:model Request.SecretValue.SshKey
type RequestSecretValueSSHKey struct {

	// SSH p r i v a t e k e y
	SSHPRIVATEKEY string `json:"SSH_PRIVATE_KEY,omitempty"`
}

// Validate validates this request secret value Ssh key
func (m *RequestSecretValueSSHKey) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request secret value Ssh key based on context it is used
func (m *RequestSecretValueSSHKey) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestSecretValueSSHKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestSecretValueSSHKey) UnmarshalBinary(b []byte) error {
	var res RequestSecretValueSSHKey
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
