// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// RequestOperationParams request operation params
//
// swagger:model Request.OperationParams
type RequestOperationParams struct {

	// connection limit
	// Minimum: -1
	ConnectionLimit int32 `json:"connection_limit,omitempty"`

	// database
	// Pattern: ^[a-z_][a-z0-9_]{0,62}$
	Database string `json:"database,omitempty"`

	// database action
	// Enum: ["database_present","database_absent","user_present","user_absent","role_present","role_absent","grant_present","grant_absent"]
	DatabaseAction string `json:"database_action,omitempty"`

	// default pool size
	// Maximum: 10000
	// Minimum: 1
	DefaultPoolSize int32 `json:"default_pool_size,omitempty"`

	// extension
	// Enum: ["postgis","pgrouting","pg_repack","pgvector"]
	Extension string `json:"extension,omitempty"`

	// extension action
	// Enum: ["extension_present","extension_absent"]
	ExtensionAction string `json:"extension_action,omitempty"`

	// max client connections
	// Maximum: 1e+06
	// Minimum: 1
	MaxClientConnections int32 `json:"max_client_connections,omitempty"`

	// max database connections
	// Maximum: 100000
	// Minimum: 1
	MaxDatabaseConnections int32 `json:"max_database_connections,omitempty"`

	// object type
	// Enum: ["database","schema","table","sequence"]
	ObjectType string `json:"object_type,omitempty"`

	// objects
	// Max Items: 64
	// Min Items: 1
	// Unique: true
	Objects []string `json:"objects"`

	// owner
	// Pattern: ^[a-z_][a-z0-9_]{0,62}$
	Owner string `json:"owner,omitempty"`

	// pgbouncer action
	// Enum: ["pool_present","pool_absent","limits_update"]
	PgbouncerAction string `json:"pgbouncer_action,omitempty"`

	// pool mode
	// Enum: ["session","transaction"]
	PoolMode string `json:"pool_mode,omitempty"`

	// pool name
	// Pattern: ^[a-z_][a-z0-9_]{0,62}$
	PoolName string `json:"pool_name,omitempty"`

	// pool size
	// Maximum: 10000
	// Minimum: 1
	PoolSize int32 `json:"pool_size,omitempty"`

	// postgresql parameters
	// Min Items: 1
	PostgresqlParameters []*RequestPostgreSQLParameter `json:"postgresql_parameters"`

	// postgresql version
	// Maximum: 18
	// Minimum: 14
	PostgresqlVersion int32 `json:"postgresql_version,omitempty"`

	// privileges
	// Min Items: 1
	// Unique: true
	Privileges []string `json:"privileges"`

	// query wait timeout
	// Maximum: 86400
	// Minimum: 1
	QueryWaitTimeout int32 `json:"query_wait_timeout,omitempty"`

	// recovery target time
	// Format: date-time
	RecoveryTargetTime strfmt.DateTime `json:"recovery_target_time,omitempty"`

	// role
	// Pattern: ^[a-z_][a-z0-9_]{0,62}$
	Role string `json:"role,omitempty"`

	// schema
	// Pattern: ^[a-z_][a-z0-9_]{0,62}$
	Schema string `json:"schema,omitempty"`

	// source cluster
	// Min Length: 1
	SourceCluster string `json:"source_cluster,omitempty"`

	// update target
	// Enum: ["postgres","patroni","system"]
	UpdateTarget string `json:"update_target,omitempty"`
}

// Validate validates this request operation params
func (m *RequestOperationParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConnectionLimit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDatabase(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDatabaseAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDefaultPoolSize(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExtension(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExtensionAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxClientConnections(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxDatabaseConnections(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateObjectType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateObjects(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOwner(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePgbouncerAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePoolMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePoolName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePoolSize(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePostgresqlParameters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePostgresqlVersion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrivileges(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQueryWaitTimeout(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecoveryTargetTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSchema(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSourceCluster(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdateTarget(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequestOperationParams) validateConnectionLimit(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ConnectionLimit) { // not required
		return nil
	}

	if err := validate.MinimumInt("connection_limit", "body", int64(m.ConnectionLimit), -1, false); err != nil {
		return err
	}

	return nil
}

func (m *RequestOperationParams) validateDatabase(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Database) { // not required
		return nil
	}

	if err := validate.Pattern("database", "body", m.Database, `^[a-z_][a-z0-9_]{0,62}$`); err != nil {
		return err
	}

	return nil
}

var requestOperationParamsTypeDatabaseActionPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["database_present","database_absent","user_present","user_absent","role_present","role_absent","grant_present","grant_absent"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		requestOperationParamsTypeDatabaseActionPropEnum = append(requestOperationParamsTypeDatabaseActionPropEnum, v)
	}
}

const (

	// RequestOperationParamsDatabaseActionDatabasePresent captures enum value "database_present"
	RequestOperationParamsDatabaseActionDatabasePresent string = "database_present"

	// RequestOperationParamsDatabaseActionDatabaseAbsent captures enum value "database_absent"
	RequestOperationParamsDatabaseActionDatabaseAbsent string = "database_absent"

	// RequestOperationParamsDatabaseActionUserPresent captures enum value "user_present"
	RequestOperationParamsDatabaseActionUserPresent string = "user_present"

	// RequestOperationParamsDatabaseActionUserAbsent captures enum value "user_absent"
	RequestOperationParamsDatabaseActionUserAbsent string = "user_absent"

	// RequestOperationParamsDatabaseActionRolePresent captures enum value "role_present"
	RequestOperationParamsDatabaseActionRolePresent string = "role_present"

	// RequestOperationParamsDatabaseActionRoleAbsent captures enum value "role_absent"
	RequestOperationParamsDatabaseActionRoleAbsent string = "role_absent"

	// RequestOperationParamsDatabaseActionGrantPresent captures enum value "grant_present"
	RequestOperationParamsDatabaseActionGrantPresent string = "grant_present"

	// RequestOperationParamsDatabaseActionGrantAbsent captures enum value "grant_absent"
	RequestOperationParamsDatabaseActionGrantAbsent string = "grant_absent"
)

// prop value enum
func (m *RequestOperationParams) validateDatabaseActionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, requestOperationParamsTypeDatabaseActionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RequestOperationParams) validateDatabaseAction(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DatabaseAction) { // not required
		return nil
	}

	// value enum
	if err := m.validateDatabaseActionEnum("database_action", "body", m.DatabaseAction); err != nil {
		return err
	}

	return nil
}

func (m *RequestOperationParams) validateDefaultPoolSize(formats strfmt.Registry) error {
	if typeutils.IsZero(m.DefaultPoolSize) { // not required
		return nil
	}

	if err := validate.MinimumInt("default_pool_size", "body", int64(m.DefaultPoolSize), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("default_pool_size", "body", int64(m.DefaultPoolSize), 10000, false); err != nil {
		return err
	}

	return nil
}

var requestOperationParamsTypeExtensionPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["postgis","pgrouting","pg_repack","pgvector"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		requestOperationParamsTypeExtensionPropEnum = append(requestOperationParamsTypeExtensionPropEnum, v)
	}
}

const (

	// RequestOperationParamsExtensionPostgis captures enum value "postgis"
	RequestOperationParamsExtensionPostgis string = "postgis"

	// RequestOperationParamsExtensionPgrouting captures enum value "pgrouting"
	RequestOperationParamsExtensionPgrouting string = "pgrouting"

	// RequestOperationParamsExtensionPgRepack captures enum value "pg_repack"
	RequestOperationParamsExtensionPgRepack string = "pg_repack"

	// RequestOperationParamsExtensionPgvector captures enum value "pgvector"
	RequestOperationParamsExtensionPgvector string = "pgvector"
)

// prop value enum
func (m *RequestOperationParams) validateExtensionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, requestOperationParamsTypeExtensionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RequestOperationParams) validateExtension(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Extension) { // not required
		return nil
	}

	// value enum
	if err := m.validateExtensionEnum("extension", "body", m.Extension); err != nil {
		return err
	}

	return nil
}

var requestOperationParamsTypeExtensionActionPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["extension_present","extension_absent"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		requestOperationParamsTypeExtensionActionPropEnum = append(requestOperationParamsTypeExtensionActionPropEnum, v)
	}
}

const (

	// RequestOperationParamsExtensionActionExtensionPresent captures enum value "extension_present"
	RequestOperationParamsExtensionActionExtensionPresent string = "extension_present"

	// RequestOperationParamsExtensionActionExtensionAbsent captures enum value "extension_absent"
	RequestOperationParamsExtensionActionExtensionAbsent string = "extension_absent"
)

// prop value enum
func (m *RequestOperationParams) validateExtensionActionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, requestOperationParamsTypeExtensionActionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RequestOperationParams) validateExtensionAction(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ExtensionAction) { // not required
		return nil
	}

	// value enum
	if err := m.validateExtensionActionEnum("extension_action", "body", m.ExtensionAction); err != nil {
		return err
	}

	return nil
}

func (m *RequestOperationParams) validateMaxClientConnections(formats strfmt.Registry) error {
	if typeutils.IsZero(m.MaxClientConnections) { // not required
		return nil
	}

	if err := validate.MinimumInt("max_client_connections", "body", int64(m.MaxClientConnections), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("max_client_connections", "body", int64(m.MaxClientConnections), 1e+06, false); err != nil {
		return err
	}

	return nil
}

func (m *RequestOperationParams) validateMaxDatabaseConnections(formats strfmt.Registry) error {
	if typeutils.IsZero(m.MaxDatabaseConnections) { // not required
		return nil
	}

	if err := validate.MinimumInt("max_database_connections", "body", int64(m.MaxDatabaseConnections), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("max_database_connections", "body", int64(m.MaxDatabaseConnections), 100000, false); err != nil {
		return err
	}

	return nil
}

var requestOperationParamsTypeObjectTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["database","schema","table","sequence"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		requestOperationParamsTypeObjectTypePropEnum = append(requestOperationParamsTypeObjectTypePropEnum, v)
	}
}

const (

	// RequestOperationParamsObjectTypeDatabase captures enum value "database"
	RequestOperationParamsObjectTypeDatabase string = "database"

	// RequestOperationParamsObjectTypeSchema captures enum value "schema"
	RequestOperationParamsObjectTypeSchema string = "schema"

	// RequestOperationParamsObjectTypeTable captures enum value "table"
	RequestOperationParamsObjectTypeTable string = "table"

	// RequestOperationParamsObjectTypeSequence captures enum value "sequence"
	RequestOperationParamsObjectTypeSequence string = "sequence"
)

// prop value enum
func (m *RequestOperationParams) validateObjectTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, requestOperationParamsTypeObjectTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RequestOperationParams) validateObjectType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ObjectType) { // not required
		return nil
	}

	// value enum
	if err := m.validateObjectTypeEnum("object_type", "body", m.ObjectType); err != nil {
		return err
	}

	return nil
}

func (m *RequestOperationParams) validateObjects(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Objects) { // not required
		return nil
	}

	iObjectsSize := int64(len(m.Objects))

	if err := validate.MinItems("objects", "body", iObjectsSize, 1); err != nil {
		return err
	}

	if err := validate.MaxItems("objects", "body", iObjectsSize, 64); err != nil {
		return err
	}

	if err := validate.UniqueItems("objects", "body", m.Objects); err != nil {
		return err
	}

	for i := 0; i < len(m.Objects); i++ {

		if err := validate.Pattern("objects"+"."+strconv.Itoa(i), "body", m.Objects[i], `^[a-z_][a-z0-9_]{0,62}$`); err != nil {
			return err
		}

	}

	return nil
}

func (m *RequestOperationParams) validateOwner(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Owner) { // not required
		return nil
	}

	if err := validate.Pattern("owner", "body", m.Owner, `^[a-z_][a-z0-9_]{0,62}$`); err != nil {
		return err
	}

	return nil
}

var requestOperationParamsTypePgbouncerActionPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["pool_present","pool_absent","limits_update"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		requestOperationParamsTypePgbouncerActionPropEnum = append(requestOperationParamsTypePgbouncerActionPropEnum, v)
	}
}

const (

	// RequestOperationParamsPgbouncerActionPoolPresent captures enum value "pool_present"
	RequestOperationParamsPgbouncerActionPoolPresent string = "pool_present"

	// RequestOperationParamsPgbouncerActionPoolAbsent captures enum value "pool_absent"
	RequestOperationParamsPgbouncerActionPoolAbsent string = "pool_absent"

	// RequestOperationParamsPgbouncerActionLimitsUpdate captures enum value "limits_update"
	RequestOperationParamsPgbouncerActionLimitsUpdate string = "limits_update"
)

// prop value enum
func (m *RequestOperationParams) validatePgbouncerActionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, requestOperationParamsTypePgbouncerActionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RequestOperationParams) validatePgbouncerAction(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PgbouncerAction) { // not required
		return nil
	}

	// value enum
	if err := m.validatePgbouncerActionEnum("pgbouncer_action", "body", m.PgbouncerAction); err != nil {
		return err
	}

	return nil
}

var requestOperationParamsTypePoolModePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["session","transaction"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		requestOperationParamsTypePoolModePropEnum = append(requestOperationParamsTypePoolModePropEnum, v)
	}
}

const (

	// RequestOperationParamsPoolModeSession captures enum value "session"
	RequestOperationParamsPoolModeSession string = "session"

	// RequestOperationParamsPoolModeTransaction captures enum value "transaction"
	RequestOperationParamsPoolModeTransaction string = "transaction"
)

// prop value enum
func (m *RequestOperationParams) validatePoolModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, requestOperationParamsTypePoolModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RequestOperationParams) validatePoolMode(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PoolMode) { // not required
		return nil
	}

	// value enum
	if err := m.validatePoolModeEnum("pool_mode", "body", m.PoolMode); err != nil {
		return err
	}

	return nil
}

func (m *RequestOperationParams) validatePoolName(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PoolName) { // not required
		return nil
	}

	if err := validate.Pattern("pool_name", "body", m.PoolName, `^[a-z_][a-z0-9_]{0,62}$`); err != nil {
		return err
	}

	return nil
}

func (m *RequestOperationParams) validatePoolSize(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PoolSize) { // not required
		return nil
	}

	if err := validate.MinimumInt("pool_size", "body", int64(m.PoolSize), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("pool_size", "body", int64(m.PoolSize), 10000, false); err != nil {
		return err
	}

	return nil
}

func (m *RequestOperationParams) validatePostgresqlParameters(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PostgresqlParameters) { // not required
		return nil
	}

	iPostgresqlParametersSize := int64(len(m.PostgresqlParameters))

	if err := validate.MinItems("postgresql_parameters", "body", iPostgresqlParametersSize, 1); err != nil {
		return err
	}

	for i := 0; i < len(m.PostgresqlParameters); i++ {
		if typeutils.IsZero(m.PostgresqlParameters[i]) { // not required
			continue
		}

		if m.PostgresqlParameters[i] != nil {
			if err := m.PostgresqlParameters[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("postgresql_parameters" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("postgresql_parameters" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *RequestOperationParams) validatePostgresqlVersion(formats strfmt.Registry) error {
	if typeutils.IsZero(m.PostgresqlVersion) { // not required
		return nil
	}

	if err := validate.MinimumInt("postgresql_version", "body", int64(m.PostgresqlVersion), 14, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("postgresql_version", "body", int64(m.PostgresqlVersion), 18, false); err != nil {
		return err
	}

	return nil
}

var requestOperationParamsPrivilegesItemsEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["CONNECT","CREATE","TEMPORARY","USAGE","SELECT","INSERT","UPDATE","DELETE","TRUNCATE","REFERENCES","TRIGGER"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		requestOperationParamsPrivilegesItemsEnum = append(requestOperationParamsPrivilegesItemsEnum, v)
	}
}

func (m *RequestOperationParams) validatePrivilegesItemsEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, requestOperationParamsPrivilegesItemsEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RequestOperationParams) validatePrivileges(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Privileges) { // not required
		return nil
	}

	iPrivilegesSize := int64(len(m.Privileges))

	if err := validate.MinItems("privileges", "body", iPrivilegesSize, 1); err != nil {
		return err
	}

	if err := validate.UniqueItems("privileges", "body", m.Privileges); err != nil {
		return err
	}

	for i := 0; i < len(m.Privileges); i++ {

		// value enum
		if err := m.validatePrivilegesItemsEnum("privileges"+"."+strconv.Itoa(i), "body", m.Privileges[i]); err != nil {
			return err
		}

	}

	return nil
}

func (m *RequestOperationParams) validateQueryWaitTimeout(formats strfmt.Registry) error {
	if typeutils.IsZero(m.QueryWaitTimeout) { // not required
		return nil
	}

	if err := validate.MinimumInt("query_wait_timeout", "body", int64(m.QueryWaitTimeout), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("query_wait_timeout", "body", int64(m.QueryWaitTimeout), 86400, false); err != nil {
		return err
	}

	return nil
}

func (m *RequestOperationParams) validateRecoveryTargetTime(formats strfmt.Registry) error {
	if typeutils.IsZero(m.RecoveryTargetTime) { // not required
		return nil
	}

	if err := validate.FormatOf("recovery_target_time", "body", "date-time", m.RecoveryTargetTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RequestOperationParams) validateRole(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Role) { // not required
		return nil
	}

	if err := validate.Pattern("role", "body", m.Role, `^[a-z_][a-z0-9_]{0,62}$`); err != nil {
		return err
	}

	return nil
}

func (m *RequestOperationParams) validateSchema(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Schema) { // not required
		return nil
	}

	if err := validate.Pattern("schema", "body", m.Schema, `^[a-z_][a-z0-9_]{0,62}$`); err != nil {
		return err
	}

	return nil
}

func (m *RequestOperationParams) validateSourceCluster(formats strfmt.Registry) error {
	if typeutils.IsZero(m.SourceCluster) { // not required
		return nil
	}

	if err := validate.MinLength("source_cluster", "body", m.SourceCluster, 1); err != nil {
		return err
	}

	return nil
}

var requestOperationParamsTypeUpdateTargetPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["postgres","patroni","system"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		requestOperationParamsTypeUpdateTargetPropEnum = append(requestOperationParamsTypeUpdateTargetPropEnum, v)
	}
}

const (

	// RequestOperationParamsUpdateTargetPostgres captures enum value "postgres"
	RequestOperationParamsUpdateTargetPostgres string = "postgres"

	// RequestOperationParamsUpdateTargetPatroni captures enum value "patroni"
	RequestOperationParamsUpdateTargetPatroni string = "patroni"

	// RequestOperationParamsUpdateTargetSystem captures enum value "system"
	RequestOperationParamsUpdateTargetSystem string = "system"
)

// prop value enum
func (m *RequestOperationParams) validateUpdateTargetEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, requestOperationParamsTypeUpdateTargetPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RequestOperationParams) validateUpdateTarget(formats strfmt.Registry) error {
	if typeutils.IsZero(m.UpdateTarget) { // not required
		return nil
	}

	// value enum
	if err := m.validateUpdateTargetEnum("update_target", "body", m.UpdateTarget); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this request operation params based on the context it is used
func (m *RequestOperationParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePostgresqlParameters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequestOperationParams) contextValidatePostgresqlParameters(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.PostgresqlParameters); i++ {

		if m.PostgresqlParameters[i] != nil {

			if typeutils.IsZero(m.PostgresqlParameters[i]) { // not required
				return nil
			}

			if err := m.PostgresqlParameters[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("postgresql_parameters" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("postgresql_parameters" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RequestOperationParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestOperationParams) UnmarshalBinary(b []byte) error {
	var res RequestOperationParams
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
