// Code generated by go-swagger; DO NOT EDIT.

package models

// RequestClusterRouting Routing role map; values match Request.ClusterRoutingTarget and null removes an optional role
//
// swagger:model Request.ClusterRouting
type RequestClusterRouting any
