// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// RequestOperationStart request operation start
//
// swagger:model Request.OperationStart
type RequestOperationStart struct {

	// confirmation
	// Required: true
	Confirmation *string `json:"confirmation"`

	// preflight id
	// Required: true
	PreflightID *int64 `json:"preflight_id"`
}

// Validate validates this request operation start
func (m *RequestOperationStart) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfirmation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePreflightID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequestOperationStart) validateConfirmation(formats strfmt.Registry) error {

	if err := validate.Required("confirmation", "body", m.Confirmation); err != nil {
		return err
	}

	return nil
}

func (m *RequestOperationStart) validatePreflightID(formats strfmt.Registry) error {

	if err := validate.Required("preflight_id", "body", m.PreflightID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this request operation start based on context it is used
func (m *RequestOperationStart) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestOperationStart) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestOperationStart) UnmarshalBinary(b []byte) error {
	var res RequestOperationStart
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
