// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// ResponseClusterHealth response cluster health
//
// swagger:model Response.ClusterHealth
type ResponseClusterHealth struct {

	// backup
	// Required: true
	Backup *HealthBackup `json:"backup"`

	// dcs
	// Required: true
	Dcs *HealthDCS `json:"dcs"`

	// observed at
	// Required: true
	// Format: date-time
	ObservedAt *strfmt.DateTime `json:"observed_at"`

	// operation
	// Required: true
	Operation *HealthOperationSummary `json:"operation"`

	// recoverability
	// Required: true
	Recoverability *HealthRecoverability `json:"recoverability"`

	// routing
	// Required: true
	Routing *HealthRouting `json:"routing"`

	// topology
	// Required: true
	Topology *HealthTopology `json:"topology"`
}

// Validate validates this response cluster health
func (m *ResponseClusterHealth) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBackup(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDcs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateObservedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOperation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecoverability(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRouting(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTopology(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponseClusterHealth) validateBackup(formats strfmt.Registry) error {

	if err := validate.Required("backup", "body", m.Backup); err != nil {
		return err
	}

	if m.Backup != nil {
		if err := m.Backup.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("backup")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("backup")
			}

			return err
		}
	}

	return nil
}

func (m *ResponseClusterHealth) validateDcs(formats strfmt.Registry) error {

	if err := validate.Required("dcs", "body", m.Dcs); err != nil {
		return err
	}

	if m.Dcs != nil {
		if err := m.Dcs.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("dcs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("dcs")
			}

			return err
		}
	}

	return nil
}

func (m *ResponseClusterHealth) validateObservedAt(formats strfmt.Registry) error {

	if err := validate.Required("observed_at", "body", m.ObservedAt); err != nil {
		return err
	}

	if err := validate.FormatOf("observed_at", "body", "date-time", m.ObservedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ResponseClusterHealth) validateOperation(formats strfmt.Registry) error {

	if err := validate.Required("operation", "body", m.Operation); err != nil {
		return err
	}

	if m.Operation != nil {
		if err := m.Operation.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("operation")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("operation")
			}

			return err
		}
	}

	return nil
}

func (m *ResponseClusterHealth) validateRecoverability(formats strfmt.Registry) error {

	if err := validate.Required("recoverability", "body", m.Recoverability); err != nil {
		return err
	}

	if m.Recoverability != nil {
		if err := m.Recoverability.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("recoverability")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("recoverability")
			}

			return err
		}
	}

	return nil
}

func (m *ResponseClusterHealth) validateRouting(formats strfmt.Registry) error {

	if err := validate.Required("routing", "body", m.Routing); err != nil {
		return err
	}

	if m.Routing != nil {
		if err := m.Routing.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("routing")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("routing")
			}

			return err
		}
	}

	return nil
}

func (m *ResponseClusterHealth) validateTopology(formats strfmt.Registry) error {

	if err := validate.Required("topology", "body", m.Topology); err != nil {
		return err
	}

	if m.Topology != nil {
		if err := m.Topology.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("topology")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("topology")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this response cluster health based on the context it is used
func (m *ResponseClusterHealth) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBackup(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDcs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOperation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRecoverability(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRouting(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTopology(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponseClusterHealth) contextValidateBackup(ctx context.Context, formats strfmt.Registry) error {

	if m.Backup != nil {

		if err := m.Backup.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("backup")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("backup")
			}

			return err
		}
	}

	return nil
}

func (m *ResponseClusterHealth) contextValidateDcs(ctx context.Context, formats strfmt.Registry) error {

	if m.Dcs != nil {

		if err := m.Dcs.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("dcs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("dcs")
			}

			return err
		}
	}

	return nil
}

func (m *ResponseClusterHealth) contextValidateOperation(ctx context.Context, formats strfmt.Registry) error {

	if m.Operation != nil {

		if err := m.Operation.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("operation")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("operation")
			}

			return err
		}
	}

	return nil
}

func (m *ResponseClusterHealth) contextValidateRecoverability(ctx context.Context, formats strfmt.Registry) error {

	if m.Recoverability != nil {

		if err := m.Recoverability.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("recoverability")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("recoverability")
			}

			return err
		}
	}

	return nil
}

func (m *ResponseClusterHealth) contextValidateRouting(ctx context.Context, formats strfmt.Registry) error {

	if m.Routing != nil {

		if err := m.Routing.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("routing")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("routing")
			}

			return err
		}
	}

	return nil
}

func (m *ResponseClusterHealth) contextValidateTopology(ctx context.Context, formats strfmt.Registry) error {

	if m.Topology != nil {

		if err := m.Topology.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("topology")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("topology")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResponseClusterHealth) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseClusterHealth) UnmarshalBinary(b []byte) error {
	var res ResponseClusterHealth
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
