// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// ResponseClusterCreate Response struct for cluster creation
//
// swagger:model Response.ClusterCreate
type ResponseClusterCreate struct {

	// unique code for cluster
	ClusterID int64 `json:"cluster_id,omitempty"`

	// operation id
	OperationID int64 `json:"operation_id,omitempty"`
}

// Validate validates this response cluster create
func (m *ResponseClusterCreate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this response cluster create based on context it is used
func (m *ResponseClusterCreate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseClusterCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseClusterCreate) UnmarshalBinary(b []byte) error {
	var res ResponseClusterCreate
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
