// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// ResponseClusterDefaultName Response struct for cluster default name
//
// swagger:model Response.ClusterDefaultName
type ResponseClusterDefaultName struct {

	// name
	// Example: postgres-cluster-01
	Name string `json:"name,omitempty"`
}

// Validate validates this response cluster default name
func (m *ResponseClusterDefaultName) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this response cluster default name based on context it is used
func (m *ResponseClusterDefaultName) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseClusterDefaultName) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseClusterDefaultName) UnmarshalBinary(b []byte) error {
	var res ResponseClusterDefaultName
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
