// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// ResponseOperationDetail response operation detail
//
// swagger:model Response.OperationDetail
type ResponseOperationDetail struct {

	// actor
	Actor string `json:"actor,omitempty"`

	// affected nodes
	AffectedNodes []string `json:"affected_nodes"`

	// cluster id
	ClusterID int64 `json:"cluster_id,omitempty"`

	// final verification
	FinalVerification any `json:"final_verification,omitempty"`

	// finished
	// Format: date-time
	Finished *strfmt.DateTime `json:"finished,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// plan
	Plan []string `json:"plan"`

	// preflight snapshot
	PreflightSnapshot any `json:"preflight_snapshot,omitempty"`

	// safe next action
	SafeNextAction *string `json:"safe_next_action,omitempty"`

	// sanitized params
	SanitizedParams any `json:"sanitized_params,omitempty"`

	// started
	// Format: date-time
	Started strfmt.DateTime `json:"started,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this response operation detail
func (m *ResponseOperationDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFinished(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStarted(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponseOperationDetail) validateFinished(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Finished) { // not required
		return nil
	}

	if err := validate.FormatOf("finished", "body", "date-time", m.Finished.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ResponseOperationDetail) validateStarted(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Started) { // not required
		return nil
	}

	if err := validate.FormatOf("started", "body", "date-time", m.Started.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this response operation detail based on context it is used
func (m *ResponseOperationDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseOperationDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseOperationDetail) UnmarshalBinary(b []byte) error {
	var res ResponseOperationDetail
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
