// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// ResponsePreflightCheck response preflight check
//
// swagger:model Response.PreflightCheck
type ResponsePreflightCheck struct {

	// name
	Name string `json:"name,omitempty"`

	// ok
	Ok bool `json:"ok,omitempty"`
}

// Validate validates this response preflight check
func (m *ResponsePreflightCheck) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this response preflight check based on context it is used
func (m *ResponsePreflightCheck) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponsePreflightCheck) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsePreflightCheck) UnmarshalBinary(b []byte) error {
	var res ResponsePreflightCheck
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
