// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// ResponseVersion Version response
//
// swagger:model Response.Version
type ResponseVersion struct {

	// version
	// Example: v1.0.0
	Version string `json:"version,omitempty"`
}

// Validate validates this response version
func (m *ResponseVersion) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this response version based on context it is used
func (m *ResponseVersion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseVersion) UnmarshalBinary(b []byte) error {
	var res ResponseVersion
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
