// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// ResponseOperationStart response operation start
//
// swagger:model Response.OperationStart
type ResponseOperationStart struct {

	// operation id
	OperationID int64 `json:"operation_id,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this response operation start
func (m *ResponseOperationStart) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this response operation start based on context it is used
func (m *ResponseOperationStart) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseOperationStart) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseOperationStart) UnmarshalBinary(b []byte) error {
	var res ResponseOperationStart
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
