// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// ResponseQueryPerformanceDetail response query performance detail
//
// swagger:model Response.QueryPerformanceDetail
type ResponseQueryPerformanceDetail struct {

	// fingerprint
	Fingerprint *QueryPerformanceQuery `json:"fingerprint,omitempty"`

	// histogram
	Histogram []int64 `json:"histogram"`

	// series
	Series []*QueryPerformancePoint `json:"series"`
}

// Validate validates this response query performance detail
func (m *ResponseQueryPerformanceDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFingerprint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSeries(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponseQueryPerformanceDetail) validateFingerprint(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Fingerprint) { // not required
		return nil
	}

	if m.Fingerprint != nil {
		if err := m.Fingerprint.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("fingerprint")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("fingerprint")
			}

			return err
		}
	}

	return nil
}

func (m *ResponseQueryPerformanceDetail) validateSeries(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Series) { // not required
		return nil
	}

	for i := 0; i < len(m.Series); i++ {
		if typeutils.IsZero(m.Series[i]) { // not required
			continue
		}

		if m.Series[i] != nil {
			if err := m.Series[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("series" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("series" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this response query performance detail based on the context it is used
func (m *ResponseQueryPerformanceDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFingerprint(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSeries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponseQueryPerformanceDetail) contextValidateFingerprint(ctx context.Context, formats strfmt.Registry) error {

	if m.Fingerprint != nil {

		if typeutils.IsZero(m.Fingerprint) { // not required
			return nil
		}

		if err := m.Fingerprint.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("fingerprint")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("fingerprint")
			}

			return err
		}
	}

	return nil
}

func (m *ResponseQueryPerformanceDetail) contextValidateSeries(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Series); i++ {

		if m.Series[i] != nil {

			if typeutils.IsZero(m.Series[i]) { // not required
				return nil
			}

			if err := m.Series[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("series" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("series" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResponseQueryPerformanceDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseQueryPerformanceDetail) UnmarshalBinary(b []byte) error {
	var res ResponseQueryPerformanceDetail
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
