// Code generated by go-swagger; DO NOT EDIT.

// Package restapi autobase console
//
//	API for autobase console
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /api/v1
//	Version: 2.9.0-management.7
//
//	Consumes:
//	  - application/json
//	  - plain/text
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
