---
- name: vitabaks.autobase.operation_credentials | Authenticate before mutation
  hosts: postgres_cluster
  gather_facts: true
  become: true
  become_method: sudo
  any_errors_fatal: true
  tasks:
    - name: Set default variables
      ansible.builtin.import_role:
        name: vitabaks.autobase.common

    - name: Define bind address
      ansible.builtin.import_role:
        name: vitabaks.autobase.bind_address

    - name: Authenticate operation credentials
      ansible.builtin.import_role:
        name: vitabaks.autobase.pre_checks
        tasks_from: operation_credentials
