// Code generated by go-swagger; DO NOT EDIT.

package operation

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"postgresql-cluster-console/models"
)

// GetOperationsIDOKCode is the HTTP code returned for type GetOperationsIDOK
const GetOperationsIDOKCode int = 200

// GetOperationsIDOK OK
//
// swagger:response getOperationsIdOK
type GetOperationsIDOK struct {

	// In: Body
	Payload *models.ResponseOperationDetail `json:"body,omitempty"`
}

// NewGetOperationsIDOK creates GetOperationsIDOK with default headers values
func NewGetOperationsIDOK() *GetOperationsIDOK {

	return &GetOperationsIDOK{}
}

// WithPayload adds the payload to the get operations Id o k response
func (o *GetOperationsIDOK) WithPayload(payload *models.ResponseOperationDetail) *GetOperationsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get operations Id o k response
func (o *GetOperationsIDOK) SetPayload(payload *models.ResponseOperationDetail) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOperationsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOperationsIDBadRequestCode is the HTTP code returned for type GetOperationsIDBadRequest
const GetOperationsIDBadRequestCode int = 400

// GetOperationsIDBadRequest Error
//
// swagger:response getOperationsIdBadRequest
type GetOperationsIDBadRequest struct {

	// In: Body
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewGetOperationsIDBadRequest creates GetOperationsIDBadRequest with default headers values
func NewGetOperationsIDBadRequest() *GetOperationsIDBadRequest {

	return &GetOperationsIDBadRequest{}
}

// WithPayload adds the payload to the get operations Id bad request response
func (o *GetOperationsIDBadRequest) WithPayload(payload *models.ResponseError) *GetOperationsIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get operations Id bad request response
func (o *GetOperationsIDBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOperationsIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
