// Code generated by go-swagger; DO NOT EDIT.

package operation

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetOperationsIDHandlerFunc turns a function with the right signature into a get operations ID handler
type GetOperationsIDHandlerFunc func(GetOperationsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOperationsIDHandlerFunc) Handle(params GetOperationsIDParams) middleware.Responder {
	return fn(params)
}

// GetOperationsIDHandler interface for that can handle valid get operations ID params
type GetOperationsIDHandler interface {
	Handle(GetOperationsIDParams) middleware.Responder
}

// NewGetOperationsID creates a new http.Handler for the get operations ID operation
func NewGetOperationsID(ctx *middleware.Context, handler GetOperationsIDHandler) *GetOperationsID {
	return &GetOperationsID{Context: ctx, Handler: handler}
}

// GetOperationsID swagger:route GET /operations/{id} operation getOperationsId
//
// Get operation audit record
type GetOperationsID struct {
	Context *middleware.Context
	Handler GetOperationsIDHandler
}

func (o *GetOperationsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetOperationsIDParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
